### ISSUE TITLE
Provide option to change language

### ISSUE THREAD

**Issue by soxhi8** [nextcloud/appstore#1027]
It would be very nice to be able to change the display-language of the appstore, instead of just defaulting to the system language.

**Comment by bigcat88** [comment]
Sorry for late reply, was very busy. Does it is not currently possible?

<img width="1176" alt="image" src="https://github.com/nextcloud/appstore/assets/13381981/c0f450c9-cd8a-4c6a-955b-3bb584c58009">

**Comment by soxhi8** [comment]
Thanks for the reply! I was referring to an option in the main menu, since I do not have an account and it would be faster to compare translations this way. Often translations do not carry over the meaning of the original text perfectly, which is why I sometimes want to compare quickly.

**Comment by soxhi8** [comment]
Sure, thank you for considering the option.
