### ISSUE TITLE
Image slider changes

### ISSUE THREAD

**Issue by janibonnevier** [nextcloud/appstore#103]
As discussed on IRC with @BernhardPosselt, we want some changes to the image slider introduced with #101.

- Ditch autoscrolling.
- No cropping, adjust height automatically for each image.
    - We may want to recommend somewhere that people only upload images of the same size or aspect ratio for each app.
- Use `img`s instead of `div`s with CSS backgrounds.
- Move controls to above the slide show.
- Indicator that shows current position in slide show and also provides navigation.
    - Miniatures or simple dots/boxes/etc?
- Border around the slider? I'm personally unsure about this.
- Maximize button

Anything else?

**Comment by BernhardPosselt** [comment]
Nope thats all :)

**Comment by BernhardPosselt** [comment]
The main reason for the border is to prevent the screenshots from mixing too much with the background. The border itself should probably either be the Nextcloud blue or a light box-shadow

**Comment by BernhardPosselt** [comment]
Looks good but the following points need adjustements:

* fullscreen images should be centered vertically and horizontally (from https://css-tricks.com/centering-css-complete-guide/):
```css
.parent {
  position: relative;
}
.child {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```

* There should be a slight transparent border around the image like margin: 15px or 30px maybe?

* Closing the fullscreen view should not play any animations
