### ISSUE TITLE
App Store should be mentioned in the logo

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#105]
We need to get the App Store in somewhere, maybe the logo?

@jancborchardt @adsworth @janibonnevier

**Comment by jancborchardt** [comment]
Yeah, the layout should be like in Nextcloud itself, just put »App store« (small s, we only capitalize the first letter ;) right next to the logo.

**Comment by janibonnevier** [comment]
Should the "App store" text be translatable?

**Comment by janibonnevier** [comment]
Nvm, I'll just do it.

**Comment by BernhardPosselt** [comment]
Nah, app store is a name (and should therefore be all caps but whatever :D)
