### ISSUE TITLE
Wrong German string in /developer/apps/generate 

### ISSUE THREAD

**Issue by joendres** [nextcloud/appstore#1054]
## Details

* Browser and browser version: Firefox 113.0.2 (64-Bit) (Mozilla Firefox snap for Ubuntu) canonical-002 - 1.0
* Language for UI and preferred on pages: Deutsch 

## JavaScript Console Output

none, Console stays empty when reloading. 

## Steps to reproduce

1. Open https://apps.nextcloud.com/developer/apps/generate with German as the preferred page language

## Result

The label for the id_author_email field reads "Benötigt keine Übersetzung. Für den Appstore wird nur die formelle Übersetzung verwendet (de_DE)." 
![Screenshot](https://github.com/nextcloud/appstore/assets/16019814/283a88d0-7f87-4e30-864a-d0736fb0fe81)

## Expected Result

The label should read "E-Mail-Adresse des Autors" as in [/locale/de/LC_MESSAGES/django.po](https://github.com/nextcloud/appstore/blob/master/locale/de/LC_MESSAGES/django.po)

## What I've tried

* Switch preferred page language to English -> the label is "Author's email" as in the _(...) call in forms.py
* Checked django.po in master -> msgstr is correct
* Checked transifex -> translation is correct for de_DE and de
  * But the wrong string appears as a suggested translations for "email"
* Checked [/nextcloudappstore/scaffolding/forms.py](https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/scaffolding/forms.py) -> Line 50 looks OK
* Checked using github.dev if the wrong string is an a file in the nextcloudappstore source tree -> it's not.

**Comment by bigcat88** [comment]
should be fixed now, can someone check?

**Comment by bigcat88** [comment]
<img width="605" alt="image" src="https://github.com/nextcloud/appstore/assets/13381981/1bdc8e51-b750-4af9-b1da-754633575c63">
