### ISSUE TITLE
Cannot register because confirmation link leads to 404

### ISSUE THREAD

**Issue by szaimen** [nextcloud/appstore#1065]
## Steps to reproduce

1. Click on register
2. Enter all data
3. Click on create account
4. Get the confirmation mail
5. click on the confirmation link that looks like this: 
```
Benötigt keine Übersetzung. Für den Appstore wird nur die formelle Übersetzung verwendet (de_DE).Nextcloud App Store<mail-address>apps.nextcloud.comhttps://apps.nextcloud.com/confirm-email/<secret-token>/apps.nextcloud.com

Vielen Dank von Nextcloud App Store!

apps.nextcloud.com
```
Translated with deepl:
```
Does not require translation. For the Appstore, only the formal translation is used (de_DE).Nextcloud App Store<mail-address>apps.nextcloud.comhttps://apps.nextcloud.com/confirm-email/<secret-token>/apps.nextcloud.com

Thank you from Nextcloud App Store!

apps.nextcloud.com
```
6. See 
![image](https://github.com/nextcloud/appstore/assets/42591237/cab83a64-4814-423e-adec-a875d901505e)
(Site not found) 404

**Comment by szaimen** [comment]
FYI @DaphneMuller @bigcat88

**Comment by bigcat88** [comment]
Can not reproduce it.
Just registered second account for my test email in the Appstore
<img width="614" alt="image" src="https://github.com/nextcloud/appstore/assets/13381981/11367990-4e4e-4a2b-a576-a470bf750a16">

**Comment by szaimen** [comment]
Possibly the problem only occours when browser is set to german?

**Comment by bigcat88** [comment]
Yep, and I can't reproduce it locally(with version from GitHub repo). But I can reproduce at the apps.nextcloud.com with German language...
Will check it after AppStore update will be deployed, as currently I can't find these strings from "bad mail" at repo at all.

**Comment by vaneslie** [comment]
I have the same issue + it has been reported via contact form by other users.

**Comment by bigcat88** [comment]
should be fixed now, can someone check?

**Comment by szaimen** [comment]
Tested and works. Thanks for fixing! :)
