### ISSUE TITLE
[Request] USB Phone Backup app

### ISSUE THREAD

**Issue by upintheairsheep** [nextcloud/appstore#1103]
Please provide the following details for error reports from https://apps.nextcloud.com/. Ignore in case of a feature request.

## Details
I already know that you are going to say that I should use the mobile apps for backing up mobile devices, but no, this is a different story altogether. This is a feature request to enable a NextCloud app that enables a device to connect to the NextCloud's USB port, and when connected, uses adb backup (and to restore, adb restore) to backup and restore your phone without needing root. ADB backups have a prompt before the backup gets initiated but can be bypassed in a second by using adb shell input to simulate a keyboard pressing down, right, then enter, then optionally home. After that, the ADB backup can be browsed with a simple script that turns it into a TAR file, and optionally process it into a browsable rootfs via Andriller. ADB backups are currently deprecated and apps using Android Snow Cone's API level on Android Snow Cone or above will only backup to Google One, however using on earlier version of Android such as Red Velvet Cake or Queen Cake will backup the apps, as well as using an app targeting a version below Snowcone as well. adb shell ls in conjunction with adb pull can allow /sdcard to be backed up with the lack of the app, if the user does not want to install the app for any reason, and the backup functionalities can be made wireless (but local network) if adb tcpip is used, however this does not persist after reboot, and Red Velvet Cake and higher provide a wireless ADB function. For iOS devices, libimobiledevice will be used to be able to use iTunes backups via the idevicebackup functionality, and be untethered from the USB cable via WiFi sync but still requiring use of the home network, but persists after reboot and does not pose security risks when connected to another network. libimobiledevice also has ways to backup other data via the iTunes filesystem (not as much data as the actual backup) like photos, settings, and apps that support itunes file sharing but not files app sharing. There are also tools on github to explore iTunes backups as if they were zip files. There is also a final thing I would like to mention, and that is to consider ALEAPP and iLEAPP for parsing backups into something easy to read for a non-techie.

* Browser and browser version:
Google Chrome 114.0.5735.239, ChromeOS 114.0.5735.239 (Official Build) (64-bit) (Most garbage OS I've ever used)
## JavaScript Console Output
N/A
If unsure see http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers?answertab=votes#tab-top

## Steps to reproduce
N/A
1.
2.
3.

**Comment by joshtrichards** [comment]
Hi @upintheairsheep - What does this have to do with the NC Appstore implementation? :)

I suggest posting your ideas over at the Nextcloud Forum (https://help.nextcloud.com) to see if anyone else is interested or wishes to collaborate on this. 

Since this isn't a bug report for the appstore itself, please close this Issue out here to avoid confusion (unless you disagree with my assessment of your report). Thanks!
