### ISSUE TITLE
Http Caching via Etag to the api:apps route ('If-None-Match: "Etag"' Header) does not work

### ISSUE THREAD

**Issue by ernolf** [nextcloud/appstore#1104]
Working on a command line appstore-browser/analyzer, I stumbled over this issue:

This feature, originaly implemented by 8329b062a47dc48dc766b1cd0b844be896c62016

_Originally posted by @adsworth in https://github.com/nextcloud/appstore/issues/12#issuecomment-226999446_

and documented in the RESTAPI does not work (or I misunderstood it?)

Steps to reproduce:

```sh
root@optiplex:~/apps.nextcloud.com# curl -sI https://apps.nextcloud.com/api/v1/apps.json | grep -i etag
ETag: "2023-08-04 16:06:26.467093+00:00"

root@optiplex:~/apps.nextcloud.com# curl -o apps.json https://apps.nextcloud.com/api/v1/apps.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.7M  100 11.7M    0     0  14.8M      0 --:--:-- --:--:-- --:--:-- 14.8M

root@optiplex:~/apps.nextcloud.com# curl -o apps.json https://apps.nextcloud.com/api/v1/apps.json -H 'If-None-Match: "$(date -ur apps.json +"1-1-%Y-%m-%d %H:%M:%S.%6N+00:00")"'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.7M  100 11.7M    0     0  10.3M      0  0:00:01  0:00:01 --:--:-- 10.3M

root@optiplex:~/apps.nextcloud.com# date -ur apps.json +"1-1-%Y-%m-%d %H:%M:%S.%6N+00:00"
1-1-2023-08-04 23:13:58.758683+00:00

root@optiplex:~/apps.nextcloud.com# curl -o apps.json https://apps.nextcloud.com/api/v1/apps.json -H 'If-None-Match: "1-1-2023-08-04 23:13:58.758683+00:00"'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.7M  100 11.7M    0     0  13.9M      0 --:--:-- --:--:-- --:--:-- 13.9M
```

What I did:
1. I loaded the Etag from the server as information.
2. I downloaded the apps.json from the server into apps.json in the working directory
3. Imediately caled the curl string again with the Etag string in the form like described [here](https://github.com/nextcloud/appstore/blob/master/docs/restapi.rst#get-all-apps-and-releases) in the RESTAPI
But even though the etag from the server is older than the local generated etag, it downloaded everything, as you can see.
4. Generated etag to not generate it in a subshell while invoking curl call
5. Caled curl again, now with generated Etag but downloaded everything again.

That should not be if I understand the purpose of the *`'If-None-Match: "Etag"'`* mechanism right and I can imagine, that it costs a lot of trafic.

The same behaviour with categories.json

Hope this helps

**Comment by bigcat88** [comment]
Thanks you for pointing on it, need to understand what is the better way to do and what to do if needed to do.

>    But even though the etag from the server is older than the local generated etag, it downloaded everything, as you can see.

Thant's expected behaviour:
```
A cache validates a file that uses ETag by sending an If-None-Match header with one or more ETag validators in the request. For example, If-None-Match: "17f0ddd99ed5bbe4edffdd6496d7131f". If the server’s version matches an ETag validator on the list, it sends status code 304 (Not Modified) in its response. If the version is different, the server responds with status code 200 (OK) and the updated resource.
```

https://datatracker.ietf.org/doc/html/rfc9110.html#section-13.1.2

And if correct `ETag` was send then the reply is `304`.

Is it enough to just update the documentation for this and not change the behavior, at least for now?

**Comment by ernolf** [comment]
> And if correct ETag was send then the reply is 304.
>
> Is it enough to just update the documentation for this and not change the behavior, at least for now?

OK. So then the documentation is wrong or at least easy to misunderstand when it says, that the etag have to look like this:
`"1-1-%Y-%m-%d %H:%M:%S.%6N+00:00"`

instead of thsi:

`"%Y-%m-%d %H:%M:%S.%6N+00:00"`

It works as expected with etag in the latter form:

```sh
root@optiplex-380-0:~# curl -o apps.json -D apps.header https://apps.nextcloud.com/api/v1/apps.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.0M  100 12.0M    0     0   188k      0  0:01:05  0:01:05 --:--:-- 1260k
root@optiplex-380-0:~# grep -iE "(http/|etag)" apps.header
HTTP/1.1 200 OK
ETag: "2023-09-07 08:20:20.629520+00:00"

root@optiplex-380-0:~# ETag="$(grep -ioP 'etag: "\K[^"]+' apps.header)"

root@optiplex-380-0:~# eval curl -o apps.json -D apps.header https://apps.nextcloud.com/api/v1/apps.json -H \'If-None-Match: \"1-1-$ETag\"\'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.0M  100 12.0M    0     0  11.8M      0  0:00:01  0:00:01 --:--:-- 11.8M
root@optiplex-380-0:~# grep -iE "(http/|etag)" apps.header
HTTP/1.1 200 OK
ETag: "2023-09-07 08:20:20.629520+00:00"

root@optiplex-380-0:~# eval curl -o apps.json -D apps.header https://apps.nextcloud.com/api/v1/apps.json -H \'If-None-Match: \"1-1-$ETag\"\'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
root@optiplex-380-0:~# grep -iE "(http/|etag)" apps.header
HTTP/1.1 304 Not Modified
ETag: "2023-09-07 08:20:20.629520+00:00"


```
What I did:
Download file *`apps.json`* in file *`apps.json`* in working directory and *`header`* in file *`apps.header`* in working directory:
`curl -o apps.json -D apps.header https://apps.nextcloud.com/api/v1/apps.json`
Show http response code and ETag stored in *`apps.header`*
`grep -iE "(http/|etag)" apps.header`

Assign *`ETag`* variable with the value of the server ETag:
`ETag="$(grep -ioP 'etag: "\K[^"]+' apps.header)"`

Download with '`If-None-Match:  "1-1-$ETag"`':

`eval curl -o apps.json -D apps.header https://apps.nextcloud.com/api/v1/apps.json -H \'If-None-Match: \"1-1-$ETag\"\'`

which responds with `200`

and with  '`If-None-Match:  "$ETag"`':

`eval curl -o apps.json -D apps.header https://apps.nextcloud.com/api/v1/apps.json -H \'If-None-Match: \"$ETag\"\'`

which - as you can see - results in the wanted behaviour; response `304` and no new download.

But important to know, (at least for me) that it has to match exactly the ETag from the server, there is no check, if the ETag is newer or older, only if it matches EXACTLY.

Thank you. At least for me everything is clear now.
In the future I will store and use the ETag of the last download as meta information instead of continuing to use my own mechanism that compares whether local ETag is older than server ETag.

**Comment by bigcat88** [comment]
@ernolf you can test `Last-Modified` header, it should work with it now.
Feel free to open new issue if anything wrong with it.

Docs update will be on next week, if I will have enough time for that(need to move them to new place first).
