### ISSUE TITLE
Endpoint to delete an app release stopped to work

### ISSUE THREAD

**Issue by vitormattos** [nextcloud/appstore#1121]
## Scenario

To test if my credentials is OK I used the follow URL because need authorization header:

https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#get-api-token

The output of endpoint to get the API token works fine, I received a JSON with my API Token.

This:
```
curl -v -X POST https://apps.nextcloud.com/api/v1/token -u "<myUsername>:<myPassword>"
```
Returns:
```json
{"token":"<myToken>"}
```

When I try to do the follow request:

https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#delete-an-app-release

The output is a HTML file with the message `Page not found` and the status code `404 Not Found`

As explained at documentation page `HTTP 404: If the app release could not be found` but I verified the app version doing the follow request:
```
curl https://apps.nextcloud.com/api/v1/platform/27.0.2/apps.json| jq '.[]|select(.id=="<myAppId>")'
```
and the version that I used to mount my URL to delete endopint, exists. I also verified on web interface at app page.

## Motivation

I need to delete a release because I launched a release with wrong version number at info.xml

## Steps to reproduce

This:
```
curl -v -X DELETE https://apps.nextcloud.com/api/v1/apps/<myAppId>/releases/<myAppVersion> -u "<myUsername>:<myPassword>"
```
Returns:

```html
   ...
    <h1>Page not found</h1>

    <p>The page you are looking for does not exist!</p>
   ...
```

PS: I used this URL: https://apps.nextcloud.com/api/v1/apps/l10n_override/releases/2.1.0

## Expected

* **HTTP 204**: If the app release was deleted successfully

**Comment by bigcat88** [comment]
https://github.com/nextcloud/appstore/blob/f94b1766680b034079b0e1394b9256c0eafc95c6/nextcloudappstore/api/v1/urls.py#L31C40-L38

This looks like a bug to me, I'll check, probably, all the time the AppStore existed, there was a partially working regular expression for parsing `app_id` during release removal, it does not allow numbers in AppId during release removal.

**Comment by bigcat88** [comment]
@vitormattos already deployed, feel free to check

**Comment by vitormattos** [comment]
Worked fine @bigcat88!
Thanks a lot!
Closing this issue.

**Comment by bigcat88** [comment]
Thank you @vitormattos for pointing out the problem and for the nice report that made it easy to fix.
