### ISSUE TITLE
Can't upload new release[CSRF check failure]

### ISSUE THREAD

**Issue by v1r0x** [nextcloud/appstore#1135]
Please provide the following details for error reports from https://apps.nextcloud.com/. Ignore in case of a feature request.

## Details

* Browser and browser version: Firefox 117

## JavaScript Console Output

```
POST https://apps.nextcloud.com/api/v1/token                                  [HTTP/1.1 403 Forbidden 70ms]

Details: "CSRF Failed: Origin checking failed - https://apps.nextcloud.com does not match any trusted origins."

```

## Steps to reproduce

1. Go to [Upload new release](https://apps.nextcloud.com/developer/apps/releases/new)
2. Enter Release-Link and Signature
3. Click on Upload Button
4. This error is shown
![image](https://github.com/nextcloud/appstore/assets/9248714/ffd7bc81-b2f2-493b-a257-e7ee6c94452b)

**Comment by bigcat88** [comment]
Thank you for reporting this, working on it.

**Comment by bigcat88** [comment]
@v1r0x Can you please recheck now?

**Comment by v1r0x** [comment]
Works as expected again. Thanks for the quick fix @bigcat88 ! :heart:

**Comment by bigcat88** [comment]
@andrey18106, thanks for helping me in this.
_Django 4 requires CSRF_TRUSTED_ORIGINS in config..._
