### ISSUE TITLE
l10n: Remove string from Transifex

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/appstore#1153]
https://github.com/nextcloud/appstore/blob/25f19514911e1225ad2dd555346fd6b9d6ed3702/nextcloudappstore/core/models.py#L451

https://github.com/nextcloud/appstore/blob/25f19514911e1225ad2dd555346fd6b9d6ed3702/nextcloudappstore/core/models.py#L472

@bigcat88 These are non-valid strings for our Translators. Please remove them or adapt them.

**Comment by bigcat88** [comment]
@rakekniven I created PullRequest to solve this problem.

Thank you very much, my mistake indeed.
