### ISSUE TITLE
Add Http Caching via Etag to the api:apps route

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#12]
Both apps and app releases provide a lastModified field. This field contains the modified date down to miliseconds.

If a request comes in, the http headers should be checked for **If-None-Match**. A lookup in the database should determine if there is an app or release with a newer last modified date. If there is none, a Http 304 should be returned without further querying the database.

If there is a newer entry, the entire thing should be served again. An Etag header should be set on the response which contains the latest lastModified from both apps and releases.

**Comment by adsworth** [comment]
implemented by #8329b062a47dc48dc766b1cd0b844be896c62016
