### ISSUE TITLE
Image resizing with CSS in fullscreen slideshow

### ISSUE THREAD

**Issue by janibonnevier** [nextcloud/appstore#120]
Resizing is currently done with JS. Ideally it would be done with only CSS. The viewed image must under all circumstances... 
- ...be as big as possible, but not bigger than its actual size.
- ...be entirely contained within the padding of `div.content-area`, that is, fully visible and not closer than 30 px from the edges of the window.
- ...maintain the correct aspect ratio.
- ...be centered vertically and horizontally within `div.content-area`, but this is already accomplished with CSS.

Using a background image and setting `background-size: contain;` is not what we are looking for, because while it does provide the right resizing behaviour, we want to use an `<img>`.

**Comment by BernhardPosselt** [comment]
This is solved using the fullscreen api
