### ISSUE TITLE
Highest Nextcloud version always shows Nextcloud 9

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/appstore#1206]
Not sure if this was there before the new design (which looks awesome btw.) but I'd rather expect this to show the latest version (e.g. 27 instead of 9)

<img width="314" alt="Screenshot 2023-11-08 at 12 32 18" src="https://github.com/nextcloud/appstore/assets/3404133/f4730a6a-9f82-4a3b-a481-c5c560634bdf">

**Comment by bigcat88** [comment]
This soon will be fixed, waiting for CI to merge fix

**Comment by bigcat88** [comment]
Fixed in: https://github.com/nextcloud/appstore/pull/1205
