### ISSUE TITLE
Sign in with GitHub page looks a bit dated

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/appstore#1207]
Probably also needs some adjustment to match the new design:

<img width="1215" alt="Screenshot 2023-11-08 at 12 30 02" src="https://github.com/nextcloud/appstore/assets/3404133/6efe4523-dda3-463b-bc07-a1552a8f5fcb">

**Comment by bigcat88** [comment]
@juliushaertl Thanks for reporting.

If something else except this is not as it expected with this update, we will be glad to fix :)

**Comment by juliushaertl** [comment]
Thanks for the hard work on that :) Looks awesome ❤️
