### ISSUE TITLE
Hide "nightly release" if there is a higher stable version

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/appstore#1209]
Ref https://apps.nextcloud.com/apps/spreed

### Screenshot

Actual | Expected
---|---
![grafik](https://github.com/nextcloud/appstore/assets/213943/fbaac759-0ecf-4695-8c7e-bf25340fb899) | ![grafik](https://github.com/nextcloud/appstore/assets/213943/e7fb059a-47f5-4f09-8119-747898d62279)

I find it a bit confusing otherwise, because the assumption could be that you do NOT receive the latest stable version when you are on the nighly channel (aka beta channel on Nextcloud Server)

**Comment by bigcat88** [comment]
<img width="891" alt="image" src="https://github.com/nextcloud/appstore/assets/13381981/1efd9501-a5ec-491b-ab3c-58fb1e9c75fe">
like this?
my local DB is a bit old, here are no 28 NC version.
Unstable version displayed when it has greater version then stable.

**Comment by nickvergessen** [comment]
Yeah, that would be my expected outcome :)

**Comment by bigcat88** [comment]
_deployed_
