### ISSUE TITLE
Report / Flag Review Spam

### ISSUE THREAD

**Issue by meichthys** [nextcloud/appstore#1221]
Please provide the following details for error reports from https://apps.nextcloud.com/. Ignore in case of a feature request.

## Details

I've seen a number of reviews on apps that are obviously spam. It would be nice if there was a way to report/flag a review as potential spam - to be later reviewed by the Nextcloud team.

One example of potential spam is the review on this app: https://apps.nextcloud.com/apps/memories

User: `pdo' pdowski`
Review content: `"><img%20src="https://webhook.site/700c721c-e6be-47ae-8fad-2db54c17ccf9">`

**Comment by Fred-Zweig** [comment]
You are right. Many reviews are abusive or spam. Other developers signaled this problem [here](https://github.com/nextcloud/appstore/issues/1215) and [here](https://github.com/nextcloud/appstore/issues/947). We hope that someone from the Nextcloud team will implement a way to report such reviews, so that later they can be checked by an admin and removed.

**Comment by bigcat88** [comment]
@andrey18106 can we easy implement this?

From frontend part we need a button on each comment only for the App author, that will set new field(`appeal`) in `AppRating` model to 1/True

And for Admins we implements the same page as "apps.nextcloud.com/account/integrations" but for reviewing marked Ratings.

Should not be very difficult, imho. What do you think?

**Comment by alexanderdd** [comment]
Hm, I am logged in (regular user) but I don't see a "report"-button for ratings? 

For example, in English this page https://apps.nextcloud.com/apps/documentserver_community has a comment "**** THE RELEASERS!" which I wanted to report.

**Comment by bigcat88** [comment]
> Hm, I am logged in (regular user) but I don't see a "report"-button for ratings?

currently **only** authors of apps can report comments
