### ISSUE TITLE
Lost certificate

### ISSUE THREAD

**Issue by brenyodani** [nextcloud/appstore#1236]
Please provide the following details for error reports from https://apps.nextcloud.com/. Ignore in case of a feature request.

## Details

After an upgrade on my VM setup, I have lost the certificates for my application I develop. Could you please rewoke my certificates? 
Thank you in advance!

github repo link: 

https://github.com/nextcloud/app-certificate-requests/tree/master/rides

**Comment by mgallien** [comment]
not to be done here but only via https://github.com/nextcloud/app-certificate-requests
