### ISSUE TITLE
Change forum links for questions/discussions

### ISSUE THREAD

**Issue by tflidd** [nextcloud/appstore#1246]
In the forum, we try to reduce the number of categories to clean up a little bit. By default, the appstore likes to have a dedicated category for each app and we'd like to catch the different apps via tags. E.g. for user-migration instead of https://help.nextcloud.com/c/apps/user-migration use https://help.nextcloud.com/tag/user-migration-app.

Is it possible to change to these tag-based links?

https://help.nextcloud.com/t/broken-incoming-category-link-for-user-migration/176504 (it's an internal link for internal discussion)

**Comment by sunjam** [comment]
> user-migration instead of https://help.nextcloud.com/c/apps/user-migration use https://help.nextcloud.com/tag/user-migration-app.

This re-direction is now set within the forum itself.  Should work automatically as-is

**Comment by bigcat88** [comment]
So I can close this?

**Comment by sunjam** [comment]
Yeah, it should be possible to correct re-directs within the forum  Ideally, people will do these on forum sections before deleting them so assure the re-directs are working.

**Comment by bigcat88** [comment]
thank you
