### ISSUE TITLE
improve search results order

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/appstore#1298]
Hello everyone!

IMO the search results order should be improved. More relevant apps should be shown first.

For example, search for "mail" - the most relevant app is "Mail" which is shown in fourth row, I have to scroll to see it. Second relevant would be Snappy Mail. The other results should be below that. Rainloop is deprecated and should not be shown at all - instead, it is shown as the first result.
![Screenshot 2024-02-11 at 23-30-35 Alle Apps - App Store - Nextcloud](https://github.com/nextcloud/appstore/assets/28591861/6a2b17be-3e7d-4d38-991f-163caffd6c42)

Or search for "map" - the most relevant app is "Maps", shown in third row, I have to scroll to see it.
![Screenshot 2024-02-11 at 23-33-43 Alle Apps - App Store - Nextcloud](https://github.com/nextcloud/appstore/assets/28591861/5b4b1985-0d08-4158-bd97-9bbed66ba618)

Thanks for reading =)

**Comment by alexanderdd** [comment]
another example: a search for "contacts" returns the official contacts app only in 6th place, off the screen (need to scroll to see it)

**Comment by edward-ly** [comment]
Sounds nice in theory, but if you're sorting by rating, then the current output should be expected, I think. And the "Featured" filter already gets rid of most apps including Rainloop.

So perhaps a new "Relevance" sorting option should be added to handle this? The sorting order could be something like:

1. Exact match in app name
2. Any other matches in app name
3. Any matches in app summary
4. Any matches in app description

Then, results within each group could be sorted by rating -> last update -> A-Z.

**Comment by edward-ly** [comment]
And if the search query is empty (e.g. when visiting the homepage), the "Relevance" sort order could be a popularity sort based on number of reviews or other relevant metrics. Featured apps would also be moved to the top, while outdated apps would be moved to the bottom.

**Comment by alexanderdd** [comment]
Thank you @edward-ly it works like a charm now! :partying_face: :tada:
