### ISSUE TITLE
Provide a way to let a developer specify supported app versions

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#130]
Since we plan to host all app releases on the store we need a way to tell users which use the app if they can expect support for their current Nextcloud version.

Think of a dev who only supports the latest version which runs on the latest Nextcloud version(thats me ;D ): The releases page for older Nextcloud releases should provide a visual hint (maybe red or orange bg that these versions are unsupported) that those versions can be used but that they are unsupported.

Similarly a typical user running Nextcloud 9.0 should be warned if an installed app only supports versions which require Nextcloud 9.1. Otherwise he might keep running a vulnerable version of the app

**Comment by janibonnevier** [comment]
It may be relevant to let devs also specify how long they intend to support the platform versions that they currently support. Simply saying that an app is currently supported is not that helpful if that support is about to be dropped in two weeks.

**Comment by BernhardPosselt** [comment]
I dont think we need a time span. Support is usually tied to supported Nextcloud versions, e.g. Calendar supports ownCloud 8, 8.1 and 9.0 (which are officially supported), News only supports 9.0

If we use the latest version as indicator if an app is still supported for a platform then the range of versions listed in \<owncloud> can be used for that. For example Calendar could publish new versions using \<owncloud min-version="8" max-version="9.0"/>. Then all older versions would simply get a red background.

However an app dev could decide to support ownCloud 8.0 by simply incrementing the patch release for 1.0.x (e.g. 1.0.25) while 9.0 will be supported using the 2.0.x release.

PS: maybe I'm also overthinking this ;)

**Comment by BernhardPosselt** [comment]
Maybe we should add an additional xml tag which contains the supported versions:
```xml
<supported-versions>
    <version min-version="1.0" max-version="1.0"/>
    <version min-version="2.0" max-version="2.0"/>
</supported-versions>
```
Both attributes are required. Support for the latest version is always implied, the tags just adds information for old versions. The above version would mark the following versions as supported:
* Latest release
* Latest 1.0.x release
* Latest 2.0.x release

These attributes would be saved on the App model.

**Comment by BernhardPosselt** [comment]
Ok, complexity spirals out of control :)

I'm closing this until someone has an easier and better idea.
