### ISSUE TITLE
Allow transfer of app ownership

### ISSUE THREAD

**Issue by janibonnevier** [nextcloud/appstore#131]
I believe it should be possible to transfer ownership of an app from one user to another. There are several scenarios where this would be relevant, e.g. if an app is sold or handed over to someone else to manage. A developer might also want to move an app between two of his own accounts, say for example that he has one personal account and one for his business. 

Obviously such an action should only be initiated by the current owner of the app, but the potential new owner must also be able to accept or decline. 

Another thing to consider is whether the users of an app would like to know about any changes in ownership.

**Comment by BernhardPosselt** [comment]
:+1:

**Comment by andyboeh** [comment]
I would love to see this fixed, as I need to transfer the ownership of an app to a new maintainer. Until then, what's the best way to transfer app ownership?

**Comment by janibonnevier** [comment]
Sorry, I've been too busy to work on this :( 

Right now you need an app store administrator to change the owner manually for you. Unsure whether they will see this here, but otherwise you should be able to find them on IRC (Freenode #nextcloud-dev).

**Comment by BernhardPosselt** [comment]
@andyboeh just create a ticket. We probably will verify it using a signature over some value using the app's certificate. More on that in a separate ticket.
