### ISSUE TITLE
Style social signup

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#135]
Currently social signup looks like this

![style](https://cloud.githubusercontent.com/assets/195053/16895203/c3c06344-4b6e-11e6-8d13-3f2d62142037.png)

This does not fit the overall style on the website. To change that, override the signup template in templates/socialaccount/signup.html by copying the template from https://github.com/pennersr/django-allauth/blob/master/allauth/templates/socialaccount/signup.html and making adjustments similar to https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/core/templates/account/signup.html

**Comment by janibonnevier** [comment]
@adsworth I'm having trouble configuring my dev setup for social accounts, so `/social/signup/` just redirects me to `/login/`. I've created an OAuth application on GitHub and acquired the Client ID and secret for it. I've created a "Social application" in the site admin using those. What am I missing?

**Comment by adsworth** [comment]
@janibonnevier did you select the site the github token is valid for? i.e. the last multiple select select box on the social application edit page.
Also do you have SITE_ID = 1 (in the admin make sure that the example.com site really has the ID 1) in your development settings.

**Comment by adsworth** [comment]
The screenshot from @BernhardPosselt is strange. When I tested on my setup. I was signed up and logged in without any pages or forms displayed first to confirm, which is what I would expect with a third party sign up.
I'll check again on my setup to see whether I can duplicate @BernhardPosselt behaviour.

**Comment by janibonnevier** [comment]
Clicking the GitHub login does lead me to GitHub where I can grant the app store access to my account. However when I do so, I'm returned to the app store to a "KeyError at /github/login/callback/". Do I need to set something special as "callback" on GitHub?

> did you select the site the github token is valid for? i.e. the last multiple select select box on the social application edit page.
Also do you have SITE_ID = 1 (in the admin make sure that the example.com site really has the ID 1) in your development settings. 

Yes . I have renamed `example.com` to `127.0.0.1:8000`. Is that bad?

As has been pointed out elsewhere, the docs are a bit of a mess, so I might just give up soon (and obviously if this issue turns out to be irrelevant altogether).

**Comment by adsworth** [comment]
I'm guessing this has to do with csp and that it breaks the views that github calls or something similar.

**Comment by BernhardPosselt** [comment]
@adsworth I dont think so :)

javascript console however should give you some hints about that

**Comment by adsworth** [comment]
If I signup with github I get the following page after clicking on github on the signup page.
![auswahl_137](https://cloud.githubusercontent.com/assets/33533/17037115/adb114fc-4f8f-11e6-9b7e-595753317424.png)

**Comment by adsworth** [comment]
@janibonnevier does sending emails work on your dev setup?

**Comment by janibonnevier** [comment]
@adsworth Yup, now it does and normal user registration works incl. email verfication. Still getting the key error when attempting GitHub signup.

**Comment by BernhardPosselt** [comment]
BTW, i think you get that weird signup page when the mail is already registered, e.g. test@mail.com is already registered, you sign up via github and have the same mail then it will show you a form where you can set a new mail instead of sending the confirmation mail regarding the social signup styling ticket

**Comment by BernhardPosselt** [comment]
Docs and infrastructure should be in place now to work on it btw
