### ISSUE TITLE
New subitems "Nextcloud Hub" and "Nextcloud minimal"

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/appstore#1406]
There is a difference between Nextcloud and Nextcloud Hub. Among other things, there is this excerpt from a video https://youtu.be/AjJ81xjUkdk?t=4817 . Wouldn't it be nice to put all the apps that belong to Nextcloud Hub in a separate sub-item? Or even a sub-item for the minimum apps required for an installation?

**Comment by sunjam** [comment]
There is no difference.  It is simply a different naming scheme for marketing.  They are exactly the same.

**Comment by edward-ly** [comment]
Yes, I don't see a need to separate the Hub apps either. And the minimal apps are already bundled with the server anyway.
