### ISSUE TITLE
a certain width of viewport messes up header area

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/appstore#1411]
* Browser and browser version: latest Firefox and Chromium

## Steps to reproduce

1. try different widths of your browser window
2. they all look kinda nice and readable, but one of them will look like this - it should be prettier:

![image](https://github.com/nextcloud/appstore/assets/28591861/807cfe17-5dbf-4420-89bf-699a62cbfdd0)

**Comment by edward-ly** [comment]
Looks like a duplicate of #1214 to me?

**Comment by bigcat88** [comment]
> Looks like a duplicate of #1214 to me?

looks like yes

**Comment by alexanderdd** [comment]
ah, sorry.

**Comment by alexanderdd** [comment]
ah, sorry.
