### ISSUE TITLE
Updated icon for Dashboard category

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/appstore#1420]
After some discussion in the design channel, we came to the conclusion the current Dashboard icon is a bit confusing, and it would be better to use the following one:
https://fonts.google.com/icons?selected=Material+Symbols+Outlined:view_column:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=column&icon.size=24&icon.color=%235f6368

cc @bigcat88 @susnux

**Comment by susnux** [comment]
For server this is now fixed, so only needs to be fixed for AppStore right now.
