### ISSUE TITLE
API is missing display of apps owner

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/appstore#143]
Currently we display who is the author of the app in the Nextcloud interface. I think the following  values in https://apps.weasel.rocks/api/v1/platform/9.0.0/apps.json would make sense:

```
"author": {
  "id": "UniqueUsername", // used for generation to profile page if we ever have any
  "displayName": "Hans Muster" // Something we can display in the interface directly
}
```

Thoughts, @BernhardPosselt?

**Comment by LukasReschke** [comment]
As start it would be acceptable to have "displayName" just display the user ID. Then we have however a more stable API for the future.

**Comment by BernhardPosselt** [comment]
We used to import the authors in the info.xml for that, but stopped doing that, reason being that its not accurate. Same goes for the owner on the store, he's just the guy who uploaded it. I also think it's not interesting for users.

I think we want to parse an AUTHORS.md file at some point and fall back to the authors in the info.xml.
