### ISSUE TITLE
Make it clearer when apps have 'graduated' to become shipped apps

### ISSUE THREAD

**Issue by raboof** [nextcloud/appstore#1456]
I was confused by https://apps.nextcloud.com/apps/twofactor_totp which claims this app is only available for old versions of Nextcloud. Instead, this app 'graduated' to being a shipped app, so it no longer needs to be installed through the app store.

It would be nice if this could be made clearer in the app store :)

**Comment by susnux** [comment]
Duplicate of https://github.com/nextcloud/appstore/issues/1380
