### ISSUE TITLE
Improve app search

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/appstore#1466]
I often find myself searching for something and the results are not showing what I want.
For example search apps by their ID does not work at all. For the average user this is less relevant, but for admins or developers who know the app IDs it is annoying.
I don't know what fields are used for searching right now, but I think it makes sense to search in app ID, app name, app summary and app description.

**Comment by edward-ly** [comment]
I did mention in https://github.com/nextcloud/appstore/issues/1298#issuecomment-2246385327 that searching by ID would be added, but it seems I forgot about that somewhere along the way. Sorry for the oversight, will fix that soon.

**Comment by provokateurin** [comment]
Oh I didn't even see that issue. I would still appreciate if this is added :)
