### ISSUE TITLE
info.xml: donation => The attribute 'title' is not allowed.

### ISSUE THREAD

**Issue by Rello** [nextcloud/appstore#1484]
when entering a donation strings, the appstore is rejecting the upload of the app.
according to the doc, this should be it

`<donation title="Become a GitHub sponsor">https://github.com/sponsors/Rello</donation>`
`info.xml did not validate: Element 'donation', attribute 'title': The attribute 'title' is not allowed.`

also type seems to be an issue
`<donation type="paypal">https://github.com/rello/analytics/wiki/donate</donation>`
`Element 'donation', attribute 'type': The attribute 'type' is not allowed`

**Comment by edward-ly** [comment]
Should be fixed in #1487 now, sorry about that!

**Comment by edward-ly** [comment]
Fix is now deployed to production.
