### ISSUE TITLE
Section for Desktop and Device apps

### ISSUE THREAD

**Issue by olantrust** [nextcloud/appstore#149]
It would be very useful to have separate sections for external apps - so people may browse and download, and find links to apps available for use with Nextcloud. 

This would massively increase the exposure of such apps and make life much easier for users (some of whom would otherwise never realise the potential). It would also make it easier for people choosing Nextcloud to see in one place what was available.

Apps for Computers
Apps for Mobiles
Apps for Tablets

They could then be filtered by operating system 
(Windows, Linux, Android, Chrome, Mac, iPhone, Games Consoles, Other Phone systems, Other Desktop systems, Other)

**Comment by BernhardPosselt** [comment]
Basically dup of #95 ;)
