### ISSUE TITLE
XSD file for schema integration and validation is outdated

### ISSUE THREAD

**Issue by janis91** [nextcloud/appstore#160]
Hi,
the schema validation fails with the file specified in the development guide:
https://apps.nextcloud.com/schema/apps/info.xsd

I think it is just outdated. Just in case you didn't have it on the list - here is a reminder.

**Comment by BernhardPosselt** [comment]
It's not outdated, it's just under development :)

Anyways, PR is up ;)

**Comment by BernhardPosselt** [comment]
Ah right, and ofc @LukasReschke needs to deploy the fixes to the server (otherwise repo only)
