### ISSUE TITLE
Login with github

### ISSUE THREAD

**Issue by JSoko** [nextcloud/appstore#162]
[While registration doesn't work because of error with the captcha (155),](https://github.com/nextcloud/appstore/issues/155)

Login with github redirects to
https://apps.weasel.rocks/github/login/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=FxdHyuaUKnSb

**Comment by mar1u5** [comment]
I think this is because of the change of the URL to apps.nextcloud.com :wink: 

@BernhardPosselt

**Comment by BernhardPosselt** [comment]
@mar1u5 I also suspect this, assigned @LukasReschke

**Comment by LukasReschke** [comment]
Should be fixed now.
