### ISSUE TITLE
Can’t register on beta app store using Github

### ISSUE THREAD

**Issue by oparoz** [nextcloud/appstore#167]
1. Got to: https://apps.nextcloud.com/login/
2. Click on the Github button
3. Give access to you Github account to Nextcloud

I should be redirected to the store, but instead I get an error 500.

@LukasReschke @BernhardPosselt

**Comment by BernhardPosselt** [comment]
We need some logs @LukasReschke  :)

**Comment by LEDfan** [comment]
Same here. The app is authorized in Github however.

**Comment by BernhardPosselt** [comment]
When did you register your account? Maybe through the URL change from apps.weasel.rocks to apps.nextcloud.com the tokens/pages dont line up anymore.

Can't reproduce it with a new account.

**Comment by janis91** [comment]
> When did you register your account?

I think that's the right question! I registered my account in the apps.weasel.rocks beta and the same error comes up for me... Maybe you could just delete these accounts and let them register again as a new user? it would be the cleanest way.

**Comment by BernhardPosselt** [comment]
Paste your usernames here and I will drop your accounts

Should not be an issue since we will probably wipe everything again before we go live

**Comment by janis91** [comment]
If the accounts will be dropped before go-live, don't bother.. I don't need a working account right now ;-)

**Comment by BernhardPosselt** [comment]
@janis91 yeah, however would be interesting to confirm if my guess is correct :D

**Comment by janis91** [comment]
@BernhardPosselt the username is, like my github account as well: janis91

**Comment by oparoz** [comment]
You can try to remove my account as well. I don't remember if I had tried to register on weasel.rocks

**Comment by BernhardPosselt** [comment]
@janis91 done, @oparoz couldnt find your user

**Comment by janis91** [comment]
@BernhardPosselt tried to login and it does not work anymore, so far so good. BUT: if i click on register and choose github, it still doesn't work. unfortunately it seems that there is another problem.

**Comment by oparoz** [comment]
>@oparoz couldnt find your user

Well, that's probably the problem. Github says I'm authorised, but I don't exist in the system.

**Comment by BernhardPosselt** [comment]
@janis91 @oparoz can you revoke the login in your github settings?

**Comment by janis91** [comment]
I did revoke the login but now i get a 500 error after giving access rights to it in github and the login is not working, either.

**Comment by oparoz** [comment]
Same here

**Comment by BernhardPosselt** [comment]
I don't see anything in the database atm. Maybe clear browser cache?

**Comment by janis91** [comment]
I did try it with another computer. It's definitely not working for me.

**Comment by BernhardPosselt** [comment]
Ok, no idea then. You could set up the store locally and debug it. Other than that I see no solution to this without server/log access @LukasReschke

**Comment by BernhardPosselt** [comment]
@janis91 @LEDfan @oparoz can you try again? should be able to get logs now ;D

**Comment by oparoz** [comment]
Here you go. You should see a couple of error 500 now :)

**Comment by LukasReschke** [comment]
```
Internal Server Error: /github/login/callback/
Traceback (most recent call last):
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 62, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 126, in dispatch
    response=access_token)
  File "/opt/appstore/venv/lib/python3.5/site-packages/allauth/socialaccount/providers/github/views.py", line 22, in complete_login
    extra_data['email'] = self.get_email(token)
  File "/opt/appstore/venv/lib/python3.5/site-packages/allauth/socialaccount/providers/github/views.py", line 32, in get_email
    email = emails[0]
```

My naive guess is that this is caused because your mail address isn't public on GitHub? Could that be it?

**Comment by LEDfan** [comment]
Done :)

**Comment by janis91** [comment]
@LEDfan @oparoz  @BernhardPosselt  I did try it with public email and it is working. I think this is the problem!

But I agree with LEDfan:

> isn't it possible to request that via the OAuth mechanism?

**Comment by BernhardPosselt** [comment]
Great that we could debug it :)

We use a library for that which is configured here: https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/settings/base.py#L138

Configuration docs are here: http://django-allauth.readthedocs.io/en/latest/configuration.html

Maybe someone can spot the missing configuration parameter :D

**Comment by BernhardPosselt** [comment]
Fix should be here https://github.com/pennersr/django-allauth/issues/369#issuecomment-200797211 :D

**Comment by janis91** [comment]
Yep. That's it! I read the OAuth API documentation and it's because the public email isn't always set, but you could add the following endpoint: [endpoint](https://api.github.com/user/emails) in order to get the private mail addresses (there has to be at least one). It should be readonly automatically.

**Comment by BernhardPosselt** [comment]
new version is live, please test ;)

**Comment by oparoz** [comment]
Worked, thanks for your support!

**Comment by oparoz** [comment]
Also, I like the workflow.

Where do we fix the email content?

**Comment by BernhardPosselt** [comment]
What content? New ticket please ;)

**Comment by BernhardPosselt** [comment]
Allauth 0.27 release notes read interesting http://django-allauth.readthedocs.io/en/latest/release-notes.html

**Comment by oparoz** [comment]
Indeed :)

**Comment by Quix0r** [comment]
I get now a message that a confirmation mail is being sent to me but nothing has reached here. I used same auth way.
