### ISSUE TITLE
Add "recommended" or "spotlighted" to the API response

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/appstore#17]
We should have a way to highlight or mark apps as spotlighted to show them more prominent in the Nextcloud user interface. This should be used for apps that we basically support but ship via the Appstore. (such as calendar or contacts)

**Comment by jancborchardt** [comment]
Shouldn’t that be »Official«?

Or a separate »Featured« tag?

**Comment by LukasReschke** [comment]
I think "Official" sets to many wrong expectations. Something like "Featured" in addition would be nice thus.

So for example once we have a bug bounty program or other more strict security policies in start. People will just start to assume that something tagged "Official" is backing that as well which it likely isn't. The term "Featured" still highlights that the app is awesome but doesn't backfire that hard directly on us in case of problems with the app.

**Comment by jancborchardt** [comment]
Ok, great. And the rest will just get featured according to their rating.
