### ISSUE TITLE
Email confirmation email should be improved

### ISSUE THREAD

**Issue by oparoz** [nextcloud/appstore#175]
I couldn't find the text for the email, so I suspect it's from some library.

Here is the content:

******************
Hello from **apps.nextcloud.com**!

You're receiving this e-mail because user oparoz at apps.nextcloud.com has given **yours as an e-mail address to connect their account**.

To confirm this is correct, go to https://apps.nextcloud.com/confirm-email/Mzc:1bZksL:Y8YI3zMQ0fOllevi3VhZ-dmiSMU/

Thank you from **apps.nextcloud.com**!
**apps.nextcloud.com**
******************

I've highlighted what should be altered.

**Comment by BernhardPosselt** [comment]
I think it's that one https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/email/email_confirmation_message.txt

To override it, copy the template into https://github.com/nextcloud/appstore/tree/master/nextcloudappstore/core/templates under the same directory and filename (/account/email/email_confirmation_message.txt) and change the bits that you want to improve.

PR welcome

**Comment by oparoz** [comment]
The problem with apps.nextcloud.com showing up everywhere is a config issue. We'll just have to remember to set the variable correctly when going into production.

Fix for the content itself is at: https://github.com/nextcloud/appstore/pull/179

**Comment by BernhardPosselt** [comment]
@oparoz fixed to config part on the website.

**Comment by oparoz** [comment]
Thanks!
