### ISSUE TITLE
Add information about supported archive format to app upload page

### ISSUE THREAD

**Issue by oparoz** [nextcloud/appstore#176]
There is no indication on the upload page about the supported archive formats. One only finds out after having uploaded an archive.
It would be good to add a small note, probably directly in the field itself

@jancborchardt

**Comment by BernhardPosselt** [comment]
Feel free to adjust the docs with a small PR https://github.com/nextcloud/appstore/blob/master/docs/developer.rst for https://github.com/nextcloud/appstore/blob/master/docs/restapi.rst#publish-a-new-app-release its already present

As for the templates: https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/core/templates/app/upload.html#L22 

Maybe change **Download URL** to **Download URL (tar.gz)**

**Comment by jancborchardt** [comment]
Also, call it »Download link« instead of the very technical »URL«. ;)

**Comment by oparoz** [comment]
Fix for the template is at: https://github.com/nextcloud/appstore/pull/178

**Comment by oparoz** [comment]
Doc fix is at: https://github.com/nextcloud/appstore/pull/180
