### ISSUE TITLE
Remove summary length restriction

### ISSUE THREAD

**Issue by oparoz** [nextcloud/appstore#177]
This is the message I got when uploading an app:

>info.xml did not validate: Element 'summary': [facet 'maxLength'] The value has a length of '1077'; this exceeds the allowed maximum length of '128'., line 13

I think this restriction should be removed. The summary is there to explain what the app is about and can be shortened automatically for areas which don't offer enough space.

**Comment by BernhardPosselt** [comment]
There are two fields: the description and summary. The summary is a very short text that will only be rendered in the list view. The description will be rendered on the app detail page.

Now for backwards compatibility: if the summary does not exist, the description will be used. Therefore you run into this error. Simply add a short \<summary> element to fix that ;)

**Comment by BernhardPosselt** [comment]
Ps: more Infos are here https://nextcloudappstore.readthedocs.io/en/latest/developer.html#app-metadata

**Comment by oparoz** [comment]
Thanks for the info, I'll test this with the next update.
