### ISSUE TITLE
Move app specific models to their own Django application

### ISSUE THREAD

**Issue by adsworth** [nextcloud/appstore#18]
We should move core.models and core.admin to core.app.models and core.app.admin and create a new core.app Django application.

If we keep everything in the core app thing will get big, messy and confusing soon.

@BernhardPosselt

**Comment by BernhardPosselt** [comment]
Yeah, after #9 is finished and merge lets think about restructuring. We could even move the app into the standard django format.

**Comment by BernhardPosselt** [comment]
Do we have a plan already?

**Comment by adsworth** [comment]
No not yet. :)

Of the top of my head I would go for something like the following:

- nextcloudappstore/api_v1 or maybe api/v1
  - app.py
  - views.py
  - urls.py
  - serializers.py
- nextcloudappstore.app
  - app.py
  - models.py
  - views.py
  - urls.py
nextcloudappstore.user
  - app.py
  - views.py
  - forms.py
  - urls.py

and then use nexttcloudappstore.core as a package with general global functionality mostly non Django related.

**Comment by adsworth** [comment]
as discussed in irc this https://gist.github.com/adsworth/83dcee2a13da3f46b87861e906bb791b is what we'll be going for.
