### ISSUE TITLE
Category for 2FA plugins

### ISSUE THREAD

**Issue by mar1u5** [nextcloud/appstore#202]
We have several plugins for our new **Pluggable 2-Factor Authentification** ... In the future there will be some more. 

Examples:

- **SMS** (https://github.com/ChristophWurst/twofactor_sms)
- **TOTP** (https://github.com/ChristophWurst/twofactor_totp)
- **U2F** (https://github.com/ChristophWurst/twofactor_u2f)

I think we should organize them in a seperate group in our appstore. What do you think?

cc @BernhardPosselt @ChristophWurst

**Comment by BernhardPosselt** [comment]
I'd probably move that into a new category called **Authentication & authorization**
