### ISSUE TITLE
Rating in app list view

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#210]
App ratings should be implemented in the app list view in the following way:

There should be two additional ways to sort apps (best to worst, no worst to best needed):
* Rating (overall)
* Rating (recent)

The app rating (overall and recent) should be shown below the screenshot in a visual way (maybe green red block like for youtube videos or stars?). Visual means: no numbers :)

**Comment by LukasReschke** [comment]
Also what about "Most installed"? – Considering the new survey client we ship with Nextcloud we can generate kinda reliable data on this :)

**Comment by BernhardPosselt** [comment]
@LukasReschke I think we've come to the conclusion that the overall rating filter should be the default.

As for most downloaded we need to think about another way to do this. Maybe regularely scrap the data off your service. Would be another ticket I think ;)

**Comment by BernhardPosselt** [comment]
Implemented
