### ISSUE TITLE
Rating an app changes the updated timestamp

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/appstore#233]
When rating an app it will be moved to the first position of the "Latest" app list.

**Comment by BernhardPosselt** [comment]
Right, because the rating on the app changed see https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/core/models.py#L73. I've also thought about if we need to decouple ratings from the actual app but that would make problems if the app rating changed in the API (if that's a problem)

**Comment by BernhardPosselt** [comment]
Another solution would be ofc to add another field like "app_updated" and only set/change that field when the app dev uploads a new release.
