### ISSUE TITLE
Markdown for reviews?

### ISSUE THREAD

**Issue by JSoko** [nextcloud/appstore#242]
Reviews shall support Markdown.
With kind of markdown? I can't get it to work...

See: https://apps.nextcloud.com/app/calendar

**Comment by BernhardPosselt** [comment]
I've added a review to https://apps.nextcloud.com/app/calendar

```
# Markdown

**check**
```

**Comment by BernhardPosselt** [comment]
BTW, we will kill the database before we go live so dont invest too much time yet :)

@jospoortvliet will probably publish an announcement once its ready

**Comment by JSoko** [comment]
Yes but, but have a look at my review for calendar:

```
[link] (https://apps.owncloud.com/content/show.php/Calendar?content=168707)
[Url=https://apps.owncloud.com/content/show.php/Calendar?content=168707]Link[/Url]
*test* _test_
```

**Comment by BernhardPosselt** [comment]
Yes, that's not markdown :)

First line must not have a space in between, second line is bb code and third line is mediawiki format

try 

```
[link](https://apps.owncloud.com/content/show.php/Calendar?content=168707)
```

**Comment by BernhardPosselt** [comment]
Syntax overview is here https://daringfireball.net/projects/markdown/syntax

**Comment by JSoko** [comment]
Thanks for clarifying...

...yes, that works.

Perhaps there should be a link to the markdown syntax?

**Comment by BernhardPosselt** [comment]
Probably. My impression was that everyone knows what Markdown is.

@LukasReschke @janibonnevier opinions?

**Comment by JSoko** [comment]
As yous see, for me as a DAU, it was not so clear as you thought...
