### ISSUE TITLE
add title and description to screenshot.

### ISSUE THREAD

**Issue by adsworth** [nextcloud/appstore#25]
needs to be available per language.

**Comment by BernhardPosselt** [comment]
Unsure if we want to got that far as to offer localized screenshots :) Thinking more of something like the three images here https://apps.owncloud.com/content/show.php/RainLoop+Webmail?content=165254

**Comment by BernhardPosselt** [comment]
@jancborchardt

**Comment by adsworth** [comment]
The screenshot doesn't need to be localized. Just the name and description.
I was thinking it would give the maintainers the chance to elaborate on what each screenshot depicts.
But then again, it seems like all other app stores and download whatevers just do the screenhots only thing.

**Comment by jancborchardt** [comment]
Just screenshots only for sure, no descriptions or titles needed. Let’s just keep it simple first, and as you said @adsworth other app stores don’t do this either.

**Comment by adsworth** [comment]
OK, I'll close it then.
