### ISSUE TITLE
Verify email addresses after E-Mail change

### ISSUE THREAD

**Issue by janibonnevier** [nextcloud/appstore#251]
When a user changes their email address, it should be verified. allauth provides some views for that which may or may not be useful. Unsure whether email addresses currently are verified at signup, but it would be appropriate for it to use the same mechanism.

**Comment by hitam4450** [comment]
This is definitely a big problem, since I changed my email address, I could not login  !
regards, hitam4450

**Comment by BernhardPosselt** [comment]
@hitam4450 you log in with your user name ;D

**Comment by hitam4450** [comment]
Thank you for reminding me......but still fails, since the systemkeeps sending a confirmation email to my obsolete and non-existing email!

reagrds, hitam4450

**Comment by GoetheG** [comment]
Got the same problem sometime when I change the e-mail address. I cannot log in with the old and with the new one. Can be a little bit annoying.
