### ISSUE TITLE
"Authentication credentials" error on Safari

### ISSUE THREAD

**Issue by Rello** [nextcloud/appstore#271]
error on MacOS & Safari (MacOS & FF48 works)
I am registered via github.
on the token-page, non is shown. when I click on "Regenerate" the following error will come up:

> {"detail":"Authentication credentials were not provided."}

same when I want to upload an app.

following errors I can see in the console when opening the Token-page:

```
token:1  
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'".

utils.js:5 
SyntaxError: Unexpected use of reserved word 'let' in strict mode

account-api-token.js:5  
SyntaxError: Unexpected use of reserved word 'let' in strict mode
```

**Comment by BernhardPosselt** [comment]
Yep, known issue. Safari 9 is not supported, we will however try to support Safari 10. 

We've got a Safari 10 fix in our repo which is not live yet, so that will take a little while ;)

**Comment by Rello** [comment]
got it. thanks

**Comment by BernhardPosselt** [comment]
We are currently working on revamping some stuff, aka getting rid of checksums in favor of required signatures. Of course all apps that are posted right now will need to be re-uploaded so we will need drop the database. 

We will of course provide quick and easy to understand documentation around all the signature stuff ;)

Things are still in beta ;D so expect it to break or be broken :)
