### ISSUE TITLE
Nightly checkbox shows "required" sign

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/appstore#283]
A little confusing

**Comment by BernhardPosselt** [comment]
We should check for a checkbox or boolean field https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/core/templates/form-fields.html#L12 and refactor the label. There should be one if and two html labels, one for required and one for optional

**Comment by BernhardPosselt** [comment]
basically:

```html
{% if field.field.required and field|field_type != 'BooleanField' %}
required label
{% else %}
optional label
{% endif %}
```
