### ISSUE TITLE
RSS feed for the appstore 

### ISSUE THREAD

**Issue by guddl** [nextcloud/appstore#294]
Hi.

"Small" feature request - it would be nice to have a RSS feed for new and/or updated  apps in the appstore.

Discussion on [help.nextcloud.com](https://help.nextcloud.com/t/rss-feed-for-the-appstore/3381)

Cheers,
Andreas

**Comment by BernhardPosselt** [comment]
The feeds should be available under:

* /feeds/releases.atom
* /feeds/releases.rss

and linked in the head https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/core/templates/base.html#L12 by using \<link> tags http://stackoverflow.com/questions/440391/how-to-tell-web-browsers-about-atom-feeds

The views should go into https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/core/views.py and the urls should added here https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/urls.py#L11

Ordering should be done by using the last_modified attribute on the AppRelease model https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/core/models.py#L323

The title should be something like **News (1.0.0)**, the description should be english description of the app rendered using markdown (the href attribute of all links needs to be sanitized, e.g. via a regex like **^https://**), the authors should be taken from the app authors and the link should be the release download link.

Use https://docs.djangoproject.com/en/1.10/ref/contrib/syndication/ for publishing the feed
