### ISSUE TITLE
info.xml interpretation - App name fallback translation

### ISSUE THREAD

**Issue by janis91** [nextcloud/appstore#297]
I will reference the issue of my app for further investigation and screenshots:
[Next Notes Issue #29](https://github.com/janis91/nextnotes/issues/29)

In short:

1. If a translation for the app description in info.xml exists, the appstore will not display the name of the app, (if there isn't a translated version of the name either). I recommend to fallback to the <name> without language information. Because most of the apps will not necessarily provide a translation for the app name, I guess.

2. A short explanation of the reason for displaying the description in a "code" block for my app [Next Notes](https://apps.nextcloud.com/app/nextnotes) would be appreciated, because I do not know what exactly causes the issue there.

Thanks!

**Comment by BernhardPosselt** [comment]
The code block is most likely due to indention since the description is rendered as markdown

**Comment by BernhardPosselt** [comment]
Ad 1.: looks like a fallback bug for django-parler

**Comment by BernhardPosselt** [comment]
Check https://github.com/nextcloud/news/blob/master/appinfo/info.xml#L6

**Comment by BernhardPosselt** [comment]
https://github.com/django-parler/django-parler/issues/159

**Comment by BernhardPosselt** [comment]
The easiest solution for this would be to always import all languages here by either taking the present translation or fetching the guaranteed to be present english translation https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/core/api/v1/release/importer.py#L152

**Comment by BernhardPosselt** [comment]
e.g.

```py
for code, _ in settings.LANGUAGES:
    translation = value.get(code, 'en')
    obj.set_current_language(code)      
    setattr(obj, key, translation)
    obj.save()
```

**Comment by janis91** [comment]
I think important is, that the language attribute isn't required for the name tag. So the fallback could always be the name tag without a language tag. If there is no name tag without `lang=""` the english version should be the primary.

**Comment by BernhardPosselt** [comment]
> I think important is, that the language attribute isn't required for the name tag. So the fallback could always be the name tag without a language tag. If there is no name tag without lang="" the english version should be the primary.

Thats how it works right now

**Comment by janis91** [comment]
But that has not worked for my apps. Both had just the name tag without language attributes and the names have not been displayed. Then after I added a language version, it worked.
