### ISSUE TITLE
Sign up should be confirmed via E-Mail

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#3]
As a user I want to confirm my sign up by clicking on a link inside an E-Mail so I can verify that I've used the correct E-Mail for future password resets.

Basic implementation should start where #2 left off and use http://django-registration.readthedocs.io/en/2.1/quickstart.html or a similarily well maintained and popular extension to implement the registration flow. 

The used library should be installed via pip and added to requirements/production.txt

**Comment by jancborchardt** [comment]
Just as a sidenote, please do not formulate issues/todos as user stories by just adding »As a user I want to …« in the front. ;) No one actually wants to go through the hassle of confirming an email address, it just has to be done.

**Comment by adsworth** [comment]
If there are no objections I would switch to https://django-allauth.readthedocs.io/ when implementing email confirmation, this would give us the added benefit of allowing registration/login via github, bitbucket and a whole bunch of other sites.

**Comment by BernhardPosselt** [comment]
Instead of django-registration?

**Comment by adsworth** [comment]
Yes, django-allauth is mentioned in the django-registration FAQ http://django-registration.readthedocs.io/en/2.1/faq.html

**Comment by BernhardPosselt** [comment]
At some point we also want to add a login with GitHub so its a good idea to get the basic framework for that in :)

I hope however that this won't have implications for the REST API.

**Comment by adsworth** [comment]
I don't think it'll have implications for the REST API. Django has built 
in support for alternate Authentication backends and as such a defined 
API for authentication. So it should be transpartent for anything that 
uses authentication.
Also building our own social authentication backend would be silly, so 
switching to allauth as early as possible is a good idea.
Cause if it does implicate the REST API we know early and not when we 
are nearly finished and everybody freaks out. :)

Am 11.06.2016 um 12:35 schrieb Bernhard Posselt:

**Comment by BernhardPosselt** [comment]
right ;)
