### ISSUE TITLE
"App can't be installed because of not allowed code in the App"

### ISSUE THREAD

**Issue by githubos1** [nextcloud/appstore#32]
OC 9.2.2. -> NC 9.0.5 @ ALL-INKL Hosted Server under PHP 7.0 (CGI)
Upgrade went fine but some Apps can not be enabled:

Hi,
when trying to ENABLE a previously in Owncloud 9.2.2. used APP:

APP: REGISTRATION 0.1.3
https://apps.owncloud.com/content/show.php?content=1706081

I get the above Error Message...

Same behaviour also in some other APPS...

Oliver

**Comment by BernhardPosselt** [comment]
Sorry, this is the repo for the new app store which is not online yet, so we can't help you here ;)
