### ISSUE TITLE
Should we offer an OCS API

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#321]
Depending on the amount of work and the server's implementation progress it I think it would be possible to implement the old app store API (I don't know how we will treat the ocs id, probably use the app id?)

This work would be for naught in the next year because new Nextcloud versions will target the new API. However it would make backporting the store to 9 and 10 very easy and possibly relieve you guys from the pressure of implementing the new API in 11. 

Thoughts, ideas? @nickvergessen @LukasReschke

**Comment by LukasReschke** [comment]
Let's get the new API in, in master and for olders give users an incentive to update :)
