### ISSUE TITLE
wrong link for back to App details link

### ISSUE THREAD

**Issue by JSoko** [nextcloud/appstore#327]
## Details

- click on an app in the appstore
- click on All versions
- scroll up and click on "<- App Details"
- link is
`https://apps.nextcloud.com/app/NAMEOFTHEAPP/`
- link should be
`https://apps.nextcloud.com/apps/NAMEOFTHEAPP/`

* Browser and browser version:
Firefox 49.01

**Comment by janibonnevier** [comment]
This does not seem to be the case on the current master branch. I'll take closer look at the latest changes.

**Comment by janibonnevier** [comment]
It was fixed here about 22 hours ago: https://github.com/nextcloud/appstore/commit/f51eb45e333afcc43adcfc82b445381336e01340#diff-98dba43714f2442a7cc4196d54ef6a09

**Comment by BernhardPosselt** [comment]
Yeah, needs another deployment @LukasReschke

**Comment by JSoko** [comment]
Is fixed now
