### ISSUE TITLE
App Versioning - Go fully semver?

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#338]
ATM our versioning scheme is basically a padded semver, digits only with a nightly boolean and last modified date in our API, e.g.

```json
{
    "version": "1.0.0",
    "nightly": true,
    "lastModified": "2016-06-25T16:49:25.319425Z"
}
```

This is fine since nightlies are not part of semver and you could also have nightlies of beta versions. If a nightly flag is true, the client needs to check the version and also display a possible update if the version is **equal** to the currently installed version. For the equal comparison the **lastModified** timestamp is the criteria (greater lastModified = greater version).

What if we expanded the spec to also allow full semver versions like: 

```json
{
    "version": "1.0.0-alpha.1",
    "nightly": false,
    "lastModified": "2016-06-25T16:49:25.319425Z"
}
```

This would require the server to use a semver library to compare the version. This would be future proof for feature requests for alphas, betas and rcs but would make apps backwards incompatible for now if they use it:

```xml
<info>
    <version>1.0.0-alpha.1</version>
</info>
```

@nickvergessen @MorrisJobke @LukasReschke @ChristophWurst @georgehrke @Henni @janibonnevier @rullzer

**Comment by nickvergessen** [comment]
I wouldn't know any reason why that would break the current system.
I think currently you can have anything as a version number 🙈

**Comment by rullzer** [comment]
I like it!

**Comment by BernhardPosselt** [comment]
@nickvergessen mentioned that pre-release versioning should work fine due to http://php.net/manual/de/function.version-compare.php which is currently used to do version comparisons. However build metadata that is postfixed with a ~ does not work, so we should not add that to your allowed regex

**Comment by nickvergessen** [comment]
> However build metadata that is postfixed with a + does not work, so we should not add that to your allowed regex

I can not see how that shouldn't work btw:
http://php.net/manual/en/function.version-compare.php
> The function first replaces _, - and + with a dot . in the version strings and also inserts dots . before and after any non number so that for example '4.3.2RC1' becomes '4.3.2.RC.1'. 

so `1.0.0~20160811` becomes `1.0.0.~.20160811`. The question is only, if `~` is lower then a number

**Comment by BernhardPosselt** [comment]
Right, however build metadata **must not** be used for comparing the version :)

**Comment by BernhardPosselt** [comment]
Basically in order to be compliant with semver, version_compare would have to strip everything after a +

**Comment by BernhardPosselt** [comment]
Implemented
