### ISSUE TITLE
Ditch discussion tag

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#340]
@georgehrke mentioned that it would be much more useful to have a full category on discourse so that you can mark questions as solved, see https://github.com/nextcloud/calendar/pull/123

We should ditch the discussion tag and instead use the discourse API to create a new category upon creating an app and link to the category instead. This would also improve info.xml compatibility with ownCloud.

@janibonnevier @nickvergessen @LukasReschke @Henni @ChristophWurst @MorrisJobke @nickvergessen

**Comment by nickvergessen** [comment]
Fine by me, not using a single topic but multiple is also a good idea.
But I wonder if this should just be the "default". Honestly, I, as an app dev, don't want to have to look in 3 discourse categories and 3 issues trackers.
So maybe it should have an option to disable?

**Comment by jospoortvliet** [comment]
so you can have sub categories. Have apps/[appsname] for example. I suggest to go that route. Disabling it completely is something we could consider allowing later, I'd start without that option.

**Comment by BernhardPosselt** [comment]
I hope the **Report problem** and **Request feature** buttons are prominent enough to prevent this kind of issue. I've discussed this issue with @jospoortvliet on IRC and we basically came to the following conclusion:
* People post threads on the forum regardless of if there's a link on the store or not. The news app has one post on the linked discussion which was posted on the forum, 3 other threads were opened in separate threads.
* If we find out that the store redirection produces too many bug reports/feature requests we should look into improving the UI, e.g. add another confirmation button that its not a bug report or feature request.
* Scrap the discussion tag for good and go for a category based approach
