### ISSUE TITLE
strange php error message

### ISSUE THREAD

**Issue by mightyBroccoli** [nextcloud/appstore#348]
## Details
I am using Debian with the latest php Version listed below. 

Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:        8.6

PHP 7.0.12-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
with Zend OPcache v7.0.12-1~dotdeb+8.1, Copyright (c) 1999-2016, by Zend Technologies

Nextcloud
  - version: 9.1.1.5
  - versionstring: 10.0.1

config.php
//Nextcloud Verifications
  'appcodechecker' => true,

//Apps
  'appstoreenabled' => true,
  'appstoreurl' => 'https://apps.nextcloud.com/api/v0',
  'appstore.experimental.enabled' => false,

## Error
[Email with php error](https://paste.xinu.at/goa1Yk/)
I pasted the error message to not clog up the issue. I am really confused by this error and it is occurring at least 10 times a day, I get the report email from my cron daemon thats the most annoying part.
Does somebody know who to fix this? If more Info is needed just ask :)

**Comment by BernhardPosselt** [comment]
That's basically Nextcloud trying to find updates for an application that is not uploaded to the new app store yet. Nothing to see here, move along ,)

**Comment by mightyBroccoli** [comment]
Thank you for the help :+1:
