### ISSUE TITLE
Set up staging server

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/appstore#350]

**Comment by BernhardPosselt** [comment]
Any progress here? IMHO super important

**Comment by christianlupus** [comment]
The plan here is to have a second instance of the app store running to test the newest features and potentially serving as a sandbox for development, did I get that right?

**Comment by bigcat88** [comment]
_I think that the issue can be closed, although it would be very cool to have a dev-production server, but at the moment there are no human resources for this._
