### ISSUE TITLE
Load images from proxy

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/appstore#358]
usercontent.apps.nextcloud.com is now online and fetching all new resources all thirty-seconds. I think it would be nice if we could modify the web UI to use that as well. Otherwise visitors and so on are leaked to app authors.

This can be done pretty easily. Just replace all images with `https://usercontent.apps.nextcloud.com/` appended with `base64encode('$url')`. So `https://github.com/rello/screenshots/raw/master/audioplayer_main.png` would result in `https://usercontent.apps.nextcloud.com/aHR0cHM6Ly9naXRodWIuY29tL3JlbGxvL3NjcmVlbnNob3RzL3Jhdy9tYXN0ZXIvYXVkaW9wbGF5ZXJfbWFpbi5wbmc=`

Also means we could probably stricten the CSP more.

**Comment by LukasReschke** [comment]
cc @BernhardPosselt

**Comment by BernhardPosselt** [comment]
Like the base64 approach :+1:

**Comment by BernhardPosselt** [comment]
One thing however: I'd prefer a lazy loading or push approach more than a poll for each possible nextcloud versions. At least the current api is the wrong approach IMHO.

**Comment by BernhardPosselt** [comment]
What I'm wondering about is: how can we display screen shot changes instantaneously after upload

**Comment by BernhardPosselt** [comment]
Tbh the best way I see to solve this issue is to download all screenshots when the info.xml is parsed. We put that into a folder which is served from the proposed sub domain

**Comment by LukasReschke** [comment]
For me anything works. We can either implement this directly in the appstore or add a webhook that goes from the appstore to the reverse proxy to download the data.

Just note that my Python knowledge is really limited. 😉

**Comment by BernhardPosselt** [comment]
Closed in favor of #361
