### ISSUE TITLE
Resource links not clickable on small browser windows

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/appstore#362]
## Details

* Browser and browser version:

Google Chrome 54.0.2840.59 

## JavaScript Console Output

none

## Steps to reproduce

1. Resize Browser window to 960px 
2. try to click one of the resources links 

## What is happening

class="row" is overlapping as the floating is not cleared.

![2016-11-03-122521_940x937_scrot](https://cloud.githubusercontent.com/assets/3404133/19964283/34df6bd0-a1c1-11e6-8135-d638a0db26db.png)

**Comment by BernhardPosselt** [comment]
@juliushaertl do you want to take care of it? Could be as simple as to edit https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/core/static/assets/css/style.css

**Comment by juliushaertl** [comment]
@BernhardPosselt done in #366
