### ISSUE TITLE
i18n: Blurry source code string "casted rating"

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/appstore#369]
File: appstore/nextcloudappstore/core/models.py

Lines:
        verbose_name=_('Number of recently casted ratings'), default=0)
        verbose_name=_('Number of overall casted rating'), default=0)

What does "casted" means? Something like "given"?

btw. Should second line have plural like "ratings"

See https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/appstore/100430485?q=ratings

**Comment by BernhardPosselt** [comment]
Yes, there's the phrase "to cast a vote" but not so sure anymore if you can also use it for "to cast a rating"

**Comment by BernhardPosselt** [comment]
yes, there's an **s** missing :)

**Comment by rakekniven** [comment]
Suggestion:
Number of recently submitted ratings
Number of overall submitted ratings

regarding missing "s":
@BernhardPosselt Will you fix it or should I supply PR?

**Comment by BernhardPosselt** [comment]
Would be cool if you could take it on :)
