### ISSUE TITLE
schema does not allow digits in app ids

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/appstore#370]
Apparently app ids like ``twofactor_u2f`` are not allowed by the info.xml schema. Could we change that regex to allow digits too or are there any strong arguments against that?

ref https://github.com/nextcloud/appstore/blob/e4567ce707b332ca14eb35e322bff5ec4397191b/nextcloudappstore/core/api/v1/release/info.xsd#L245-L250

**Comment by BernhardPosselt** [comment]
If it works it should not be an issue. However this would likely require you to change the regex at various other places (mainly urls) as well, for instance https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/core/api/v1/urls.py#L16

I'd grep the source for **r'** and adjust the app id specific regexes if you think this should be fixed.
