### ISSUE TITLE
Memory allocation error with PHP 7.0 and IPv6

### ISSUE THREAD

**Issue by Gummikavalier** [nextcloud/appstore#373]
## Details

* Browser and browser version:
Firefox 49.0.2

* OS:
CentOS 7

* Nextcloud version:
10.0.1

## Steps to reproduce

1. Update Nextcloud platform to PHP 7.0
2. Have IPv6 address on the server and client
3. Login with admin account and go to Apps -> 'Not enabled' page

## Result

You get a spinning circle in browser and the logs say:

`{"reqId":"XCWoX@J76rqvrWcCGd-2xQAAAAo","remoteAddr":"2001:708:10:12:eea6:6baa:fedf:81","app":"PHP","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 17179873280 bytes) at \/var\/www\/html\/nextcloud\/lib\/public\/AppFramework\/Http\/JSONResponse.php#69","level":3,"time":"2016-11-11T17:48:43+02:00","method":"GET","url":"\/settings\/apps\/categories","user":"admin"}`

**Comment by BernhardPosselt** [comment]
Not an app store issue. Not enabled apps are first of all not fetched from the app store and I suppose you didnt even set your app store url to the new app store correct?

**Comment by Gummikavalier** [comment]
I did set it at

`'appstoreurl' => 'https://apps.nextcloud.com/api/v0',`

in config.php. I removed that to see if it had any effect though. It didn't. The server doesn't actually show any apps at all, except the installed ones.

**Comment by BernhardPosselt** [comment]
Restart your webserver, its cached ;)

**Comment by Gummikavalier** [comment]
Yes, I did that too. But I was indeed jumping to conclusions anyway... I removed the IPv6 from equation and the over allocation happens still. Sorry for the trouble. :)

**Comment by BernhardPosselt** [comment]
Btw, I don't have this issue on my instance. Looks like a server issue if it is in fact a bug

**Comment by Gummikavalier** [comment]
Thanks. I looked into this with fresh brains this morning going, having deduced that it must be about cache. I expected it to be caused by asset-pipeline but it was infact APCu.

Nextcloud app page started working again after I disabled
`'memcache.local' => '\\OC\\Memcache\\APCu',`
in config.php.

I compared apcu.ini versions between
    php56w-pecl-apcu
    php70w-pecl-apcu
and there weren't any differences to them (only manual edit is apc.enable_cli=1 on both).

**Comment by Gummikavalier** [comment]
Just out of curiosity I tested PHP7.0 with Ubuntu 14.04 LTS based Nextcloud installation. No problems with APCu there. So this could be APCu version specific thing.

CentOS7
`php70w-pecl-apcu-5.1.6-1.w7.x86_64`

Ubuntu 14.04 LTS
`php-apcu    5.1.7+4.0.11-2+deb.sury.org~trusty+1  amd64`

**Comment by BernhardPosselt** [comment]
Personally I'm not that fond of APCu since a big chunck of bug reports that I get for the News app are caused by stale APCu caches. I also know that there were various broken APCu that were shipped by Ubuntu back in the days (12.04 maybe?) and the way Ubuntu maintains its stuff is not what I personally consider stable :P

But that's just me rambling :)

**Comment by Gummikavalier** [comment]
Thanks for the insight! I also found other threads about compatibility issues with APCu and PHP 7.0, so indeed it might be best to drop it from our installations. :)
