### ISSUE TITLE
Can't upload app release with number in app ID

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/appstore#374]
When uploading `twofactor_u2f` I see the following error:

> No possible app folder found. App folder must contain only lowercase ASCII characters or underscores

This seems to be caused by https://github.com/nextcloud/appstore/blob/d85b6c94f8cac930fae91d7e2c4a6590e63486f6/nextcloudappstore/core/api/v1/release/parser.py#L162-L171 which has the following regex:

```python
 self.app_folder_regex = re.compile(r'^[a-z]+[a-z_]*(?:/.*)*$')
```

That should probably also include numbers but I'm not really sure what to adjust here.

Any help, @BernhardPosselt? 😄

**Comment by LukasReschke** [comment]
cc @ChristophWurst as it affects the app from you :)

**Comment by BernhardPosselt** [comment]
@LukasReschke exactly :)

@ChristophWurst another part that was missing :D, can you create a PR? Should be super easy to fix :)

**Comment by BernhardPosselt** [comment]
PS: @LukasReschke would be cool if you could upload the archive, we've got integration test machinery in place: https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/core/api/v1/tests/test_parser.py#L186

**Comment by LukasReschke** [comment]
[twofactor_u2f (1).tar.gz](https://github.com/nextcloud/appstore/files/595524/twofactor_u2f.1.tar.gz)
