### ISSUE TITLE
Allow the dev to specify a thumbnail for listviews.

### ISSUE THREAD

**Issue by adsworth** [nextcloud/appstore#382]
1. Add thumbnail attribute to the screenshot tag in info.xml.
2. When displaying the app in a list view use a thumbnail if it exists otherwise use the full size image.
3. Expose thumbnail in API and update API docs

**Comment by Rello** [comment]
@BernhardPosselt is there a recommendation for the size of the small version?
how small should it be? what is the resolution NC is using in the store?

**Comment by BernhardPosselt** [comment]
There is no fixed size in use because of bootstrap. However 400px wide should be fine
