### ISSUE TITLE
Camel case app name at app generation

### ISSUE THREAD

**Issue by pbek** [nextcloud/appstore#385]
When I try to generate my app `QOwnNotesAPI` on <https://apps.nextcloud.com/developer/apps/generate> I get the the error message `Der App-Name muss in Kamelschrift sein. Z.B. MyApp` (means the app name has to be camel case).

Does that mean the name `QOwnNotesAPI` isn't accepted as such?

My problem is I use the name for already two years on <https://apps.owncloud.com/content/show.php?content=173817>.

**Comment by pbek** [comment]
Side note: I realised I don't need this process to get an existing app signed. But I guess this still could be an issue for new apps.

**Comment by LukasReschke** [comment]
Fixed

**Comment by pbek** [comment]
Great, thank you!
