### ISSUE TITLE
<default_enable/> not allowed in info.xml

### ISSUE THREAD

**Issue by icewind1991** [nextcloud/appstore#390]
This prevents most shipped apps from being uploaded

cc @BernhardPosselt @LukasReschke

**Comment by LukasReschke** [comment]
At the moment I don't think we should upload shipped apps. But we should change that in the future once we want to do that.

**Comment by MorrisJobke** [comment]
We should then simply remove this tag, because it is deprecated and should be hardcoded somewhere else in the server code (or in the planned app bundles)

**Comment by BernhardPosselt** [comment]
As stated before and in https://github.com/nextcloud/logreader/issues/27 the tag should not be used anymore, closing hence :)
