### ISSUE TITLE
Release version numbers like 16.09.0 are not allowed

### ISSUE THREAD

**Issue by pbek** [nextcloud/appstore#393]
When I try to submit a release for <https://apps.owncloud.com/CONTENT/content-files/173817-qownnotesapi.tar.gz> at <https://apps.nextcloud.com/developer/apps/releases/new> I get the error message: 

`info.xml did not validate: Element 'version': [facet 'pattern'] The value '16.09.0' is not accepted by the pattern '(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(\-([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?'., line 9`

With the version number `16.09.0` I follow the same version schema like for example Ubuntu does. The Nextcloud appstore disapproves of that. Is this really necessary?

I humbly ask for loosening the restraints and allowing leading zeros. :bear:

**Comment by elmanell** [comment]
If you check the docs you'll see that the app store uses semver. Semver disallows leading zeroes so I think the version you are trying to use won't work ;)

**Comment by pbek** [comment]
That would be a great pity, I'm using them the whole year for <https://apps.owncloud.com/content/show.php?content=168497>, <https://apps.owncloud.com/content/show.php/OwnBackup?content=170674> and <https://apps.owncloud.com/content/show.php/QOwnNotesAPI?content=173817>. I neither fancy to re-release everything for ownCloud (because that takes weeks to get approved and is a lot of work) nor maintaining different releases for Nextcloud.

Neither ownCloud nor Nextcloud themselves had a problem with the version number so far (nor had the ownCloud app page), only the Nextcloud store has a problem with it apparently.

Is the enforcement really necessary?

**Comment by BernhardPosselt** [comment]
Yes, because semver is cross platform and widely used and you need a standardised versioning scheme to reliably determine if one version is bigger than the other.

Check out the standard, it makes a lot of sense since it signals your users if APIs or dependencies changed. If you want to keep your versioning scheme simply drop the leading zeroes

**Comment by pbek** [comment]
Wouldn't it make sense to enforce this in Nextcloud core too so it is clear that semver is mandatory? I can't drop the zero without re-releasing everything or keeping an extra release for the Nextcloud store.

**Comment by BernhardPosselt** [comment]
Sure nextcloud should also enforce it, it just wasn't done yet ;) 

The app store was basically the first project that even bothered to create a schema.

Just create a new release if dropping a leading zero is an issue ;)

**Comment by pbek** [comment]
I now did with <https://apps.nextcloud.com/apps/qownnotesapi>.
