### ISSUE TITLE
Don’t show »Previous« and »Next« bar of screenshots when there’s only one

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/appstore#397]
It’s a bit confusing and the white square in the middle also looks more like a bug than a representation of the current screenshot.

Especially since there are a bunch of apps with only one image, the whole bar of »Previous/Next« should not be shown if there is only one screenshot.

**Comment by jancborchardt** [comment]
Thanks a lot @adsworth! :)

**Comment by adsworth** [comment]
Sadly @BernhardPosselt had to revert the commit since the missing controls messes with the slider JS and the view full screen functionality broke.
I'll see whether I can get a pure JS solution, where I just hide the controls, commited. :)

**Comment by BernhardPosselt** [comment]
It's not reverted but fixed ;) 

Just needs a deployment

**Comment by adsworth** [comment]
Ups, my bad. 

I totally missed those inline ifs to add the hidden class. 

/me reminds myself to pay better attention when reviewing.
