### ISSUE TITLE
Releases are listed wrong

### ISSUE THREAD

**Issue by janis91** [nextcloud/appstore#399]
Releases are listed wrong in my case of the ocr app.

I know the reason for this. I did not understand how the versioning of the app releases should have been done. But now I corrected my mistake. The only thing I can't edit or delete are prioir app releases. So I ask you for it:

Could you please delete all but the last two of the app releases of my ocr app for nextcloud version 10?
Otherwise it could get weird for the users.

nextcloud version 11 is fine by the way.

**Comment by BernhardPosselt** [comment]
Can you elaborate? You can use the rest api to delete releases BTW, check the docs

**Comment by janis91** [comment]
Sorry. I was very tired as i wrote that.. 

The following:
If I upload a new release (1.0.2) which aims only at NC10 it gets displayed 3 times on the download page. I guess it has something to do with the other release (2.0.0) which is only for NC11 and is already available.

**Comment by BernhardPosselt** [comment]
You are right, looks like a bug. Issue is probably that there are currently 3 nextcloud releases for 10 which are tried for your release (10.0.0, 10.0.1, 10.0.2). Compatible apps are then collected based on their requirements but there's no reduplication logic afaik

**Comment by BernhardPosselt** [comment]
Fix up, please review :)
