### ISSUE TITLE
Use Nextcloud button styles

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/appstore#402]
All the buttons are green and have sharp corners. This looks very strange, is hard to read and doesn’t seem clickable.

Instead we should use the Nextcloud button style with rounded corners. cc @nextcloud/designers

**Comment by BernhardPosselt** [comment]
All buttons now look similar (blue with no rounded corners, feedback on hover).

This should remove the confusion on what is clickable and what not. As for detailed button design I think that belongs into #468 or a similar ticket which will specifiy a concrete design language (high fidelity mockups).

**Comment by skjnldsv** [comment]
👌👍

**Comment by Espina2** [comment]
We should look on that Issue at the conference. :)

@jancborchardt @BernhardPosselt @skjnldsv

**Comment by jancborchardt** [comment]
Thabks a lot @BernhardPosselt!
