### ISSUE TITLE
Make at least one screenshot/image mandatory

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/appstore#403]
Currently it looks quite weird with the Nextcloud logo as placeholder. At least one screenshot/image per app should be mandatory, as other appstores do too.

cc @nextcloud/appstore

**Comment by BernhardPosselt** [comment]
The thing is that this breaks a lot of existing apps which could be submitted just fine. 

Last time I brought this up (mandatory small thumbnail for images) the response was overwhelmingly negative.

Apart from that you could create an app that only adds a REST API which is not configurable. There is essentially no proper way to create a screenshot for that.

cc critical folks :D @nickvergessen @MorrisJobke @LukasReschke

**Comment by jancborchardt** [comment]
Well, we shouldn’t necessarily break the existing apps but make it mandatory going forward, and nudge those devs who don’t have images added yet. It just doesn’t look proper without.

Let’s go through the current apps without screenshots:
- SMS sync app: should obviously have an image or more cc @nerzhul
- Bookmarks: same here @blizzz please add screenshots ;)
- Ownpad: @otetard also here, please add screenshots to your cool app :)
- Notes: same @Henni :)
- Preview generator: @rullzer anything like config, or how it looks, or just an image of the sidebar or the list of files with previews. Anything of it in action.
- SQL user backend: published by anonymous, not sure how that is possible. But even that app has got to have some view of it in action, even if it’s just a share list dropdown or user mgmt or so.

I don’t see a reason to not make screenshots mandatory. Otherwise app devs just miss adding one and it looks crappy in the store.

**Comment by nerzhul** [comment]
@jancborchardt i agree, just i didn't check out the documentation yet. If you have the exact line to add to info.xml tell me here and i will look at this soon

**Comment by BernhardPosselt** [comment]
It's perfectly fine for apps like provisioning api to not add any screenshots IMHO.

I think the issue here is similar to a lot of other things like one liners as descriptions or missing issue tracker/documentation links: although not required a lot of apps should actually provide more information about what they do and where to get help.

The solution to this issue is likely to file feature requests in the respective repos like you did now and educate developers through appropriate channels.

@nerzuhl's issue looks more like a discoverability issue to me which is totally cool because neither the tutorial nor many existing apps feature all of the (in most cases) sensible tags. And the app store is pretty new :).

Maybe it would make sense to create a form that allows you to see and edit all possible fields graphically. There you can also add tips and best practices. Hitting the submit button would then generate the full XML for you.

**Comment by nerzhul** [comment]
Very Nice Idea !

**Comment by otetard** [comment]
@jancborchardt Thanks for the ping, I’ve just added a screenshot for Ownpad.

Olivier;

**Comment by jancborchardt** [comment]
@BernhardPosselt can we then use the app icon as the fallback? I mainly want to encourage devs to present their app in a visually attractive manner so it’s not just placeholders and text. :)

**Comment by BernhardPosselt** [comment]
I see. The thing is an icon is also not required if you don't add a navigation entry.  Do we have a nicer default icon/image for an app than the current placeholder? 

I think once we get enough apps to feature a screenshot the peer pressure should do the rest :)

**Comment by nickvergessen** [comment]
Well just have a look at the app management, there are also icons for apps which dont have a nav entry, and if the app has none it falls back to somehting like a setting wheel.

I'd do the same in the appstore, and maybe add a warning when uploading a version without screenshot, but mandatory (upload fails) is too much I think with sql user backend being one sample.

**Comment by nerzhul** [comment]
This is now fixed:

https://apps.nextcloud.com/apps/ocsms

**Comment by jancborchardt** [comment]
Even if the app is something like adding an API or only adding settings or a user backend, a screenshot of that is better at conveying what the app does than nothing. Every app has something where a screenshot can be made of to help explain better what it does.

@nickvergessen the comparison to the system apps which fall back to the gearwheel icon is not apt here as most of these are never published on the app store.

**Comment by rullzer** [comment]
This is just stuff that makes it more annoying to add apps to the appstore.

I don't feel like adding screenshots or icons. So when this becomes mandatory I will just copy over the defaults. Which will result in an annoyed me and you. 

In short if somebody wants screenshots or icons open a PR to the app in question.

**Comment by BernhardPosselt** [comment]
BTW we already have two of such apps on the store: SQL user backend and preview generator

**Comment by BernhardPosselt** [comment]
Close this issue after bookmarks and notes have uploaded screenshots?

**Comment by jancborchardt** [comment]
Bookmarks still has no screenshot uploaded. @blizzz can you do that? :)

**Comment by BernhardPosselt** [comment]
Just needs a release afaik

**Comment by blizzz** [comment]
When it's ready ⏳

**Comment by jancborchardt** [comment]
@blizzz what does that mean? ;) Would be good to have a screenshot here.

**Comment by blizzz** [comment]
@jancborchardt it needs a release

**Comment by jancborchardt** [comment]
@blizzz then please release ;)

**Comment by blizzz** [comment]
@jancborchardt 🎉
