### ISSUE TITLE
Do not show empty monitoring category

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/appstore#407]
The monitoring category is empty:
https://apps.nextcloud.com/categories/monitoring

We shoudn’t show it in the navigation hence. :)

**Comment by BernhardPosselt** [comment]
Problem should solve itself given enough time :)

**Comment by jancborchardt** [comment]
Yeah, maybe that’s best after all ;)

**Comment by korelstar** [comment]
The category is not empty anymore :wink:

**Comment by jancborchardt** [comment]
Nice!
