### ISSUE TITLE
rewrite info.xml on upload to match required schema order

### ISSUE THREAD

**Issue by adsworth** [nextcloud/appstore#41]

**Comment by LukasReschke** [comment]
Note that apps are cryptographically signed, you can rewrite it for processing but not for delivery to the end-user 😉

**Comment by adsworth** [comment]
the rewrite is only needed during upload to the AppStore. Currently if the xml in the tarball isn't in the order the xsd requires the validation fails, even if the info.xml contains all the required information.
So we need an extra transformation to get the info.xml in the required order and validate with the schema.
As @BernhardPosselt said xml f*ckery. :)
