### ISSUE TITLE
website performance issues

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#413]
Any up to date statistics @LukasRescke ?

Stuff seems to be slow again. If it's out of memory again we should potentially investigate memory leaks

**Comment by BernhardPosselt** [comment]
@LukasReschke

**Comment by LukasReschke** [comment]
Not yet, also I don't have any big idea how to profile Python stuff. I'll see to get NewRelic running on the host. If that doesn't help another first mitigation would be to put Varnish in front of the API endpoints.

**Comment by BernhardPosselt** [comment]
No idea either how to debug php stuff. My guess is that there is some debug tool that let's you view allocated objects and where they were allocated (if it's a mem leak at all)

**Comment by BernhardPosselt** [comment]
Many API calls were apparently the cause. Varnish solved it
