### ISSUE TITLE
Wrong translation of "Organization" in German

### ISSUE THREAD

**Issue by claell** [nextcloud/appstore#426]
Small issue, but though I add it to keep track of it.

The category "Organization" should be probably translated to "Organisation" in German.

**Comment by BernhardPosselt** [comment]
Translation happens on tansifex. Same goes for translation issues (you can comment on each string) did you already sign yourself up there?

**Comment by claell** [comment]
I just requested access to the German team, but wanted to keep track of the problem with this issue until I get accepted and this is fixed.

**Comment by BernhardPosselt** [comment]
Is your handle the same on Transifex? 

@LukasReschke @MorrisJobke can you give this guy access to German and German (Germany) :)?

**Comment by claell** [comment]
No, my name is "clel" at Transifex.
Thanks for your fast respone :)

**Comment by LukasReschke** [comment]
User is accepted.

**Comment by claell** [comment]
This is strange. I just checked the translation and it seems to be correct:
![bildschirmfoto vom 2017-01-22 14-50-51](https://cloud.githubusercontent.com/assets/6171135/22182948/4edb3ba6-e0b2-11e6-979c-822df41836c8.png)

However this is how it appears currently:
![bildschirmfoto vom 2017-01-22 14-49-28](https://cloud.githubusercontent.com/assets/6171135/22182946/4cc2ece2-e0b2-11e6-8d1d-4b408275a927.png)
![bildschirmfoto vom 2017-01-22 14-50-34](https://cloud.githubusercontent.com/assets/6171135/22182947/4db96b26-e0b2-11e6-9c5c-16e8bf7ccee3.png)

**Comment by BernhardPosselt** [comment]
Ok, then it just needs another deployment I guess

**Comment by BernhardPosselt** [comment]
https://github.com/nextcloud/appstore/blob/master/locale/de/LC_MESSAGES/django.po#L1120 btw

**Comment by claell** [comment]
Might be true, but according to Transifex the translation has been submitted 5 months ago and I think there has been deployments in between according to https://github.com/nextcloud/appstore/releases

**Comment by MorrisJobke** [comment]
> Might be true, but according to Transifex the translation has been submitted 5 months ago and I think there has been deployments in between: https://github.com/nextcloud/appstore/releases

Maybe the .mo file was not generated? There is only a `makemessages` in the transifex-sync script.  When does the `compilemessages` happen? usually you do this during/before deployment. Maybe this was forgotten?

**Comment by BernhardPosselt** [comment]
It's all scripted https://github.com/nextcloud/appstore/blob/master/scripts/maintenance/update.sh

**Comment by BernhardPosselt** [comment]
Works correctly locally, so I just corrected it in the web gui :)
