### ISSUE TITLE
Move Docs into NC Developer Documentation

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/appstore#430]
What do you think? @BernhardPosselt @nextcloud/documentation

**Comment by BernhardPosselt** [comment]
The store releases independently from the server and is not supported/bundled with the commercial version.  I think things are fine as is therefore closing :)

**Comment by BernhardPosselt** [comment]
Notes and news also ship separate docs btw and calendar/contacts docs should also be shipped separately matching the apps' releases
