### ISSUE TITLE
Add a "add your rating" button/link, next to the rating

### ISSUE THREAD

**Issue by oparoz** [nextcloud/appstore#434]
## Steps to reproduce

1. Look at an app
2. Look at the rating
3. Try to add a rating

It took me a while to figure out that the way to add a rating was located at the bottom of the page. I thought I was blocking some script or that there was a problem with the app store.

It would be great to have some form of link/button which scrolls to the bottom so that the user can add a rating.

In general, I think thee is a usability issue with having all these buttons at the bottom of the page, so maybe this could be solved another way. Lots of websites have buttons at the top which link to the different sections found lower on the page.

@jancborchardt

**Comment by BernhardPosselt** [comment]
Maybe we could add that link/button in addition to the current one to the right of the current ratings, e.g. 

Overall Rating
Very Positive ([Add rating]())

**Comment by oparoz** [comment]
That would work for me, that's the first place I looked.

**Comment by jancborchardt** [comment]
Yes. The button could be labeled »Add your rating«. :)

Also, the buttons don’t look like buttons and are all green, which adds to the confusion. It would be best to just take the button styles from the server which people are used to. :) cc @nextcloud/designers

**Comment by BernhardPosselt** [comment]
Btw, I think there are actually no green buttons left :D (just blue ones)

**Comment by jancborchardt** [comment]
I’m seeing this right now ;)

![capture du 2017-03-30 00-23-20](https://cloud.githubusercontent.com/assets/925062/24479497/e33d721c-14df-11e7-9861-9dffd70cfec9.png)

**Comment by bigcat88** [comment]
We have already made a new design, I’ll close this issue for now, because the “rate the app” button is already visible above the comments, and it’s hard not to notice it
