### ISSUE TITLE
At least a single resource for support or contact should be required

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/appstore#438]
This is simply asking us for trouble. No repo. No website. Nothing. The app was provided only over an archive on Google Drive (https://github.com/nextcloud/app-certificate-requests/pull/52) ... this is not offending developers, google drive or anything 😅 But - you know what I mean I hope 😢 

<img width="919" alt="bildschirmfoto 2017-03-01 um 11 44 38" src="https://cloud.githubusercontent.com/assets/19711361/23456641/8c1a9b1c-fe74-11e6-9894-e0fec0f622e7.png">

**Comment by BernhardPosselt** [comment]
Ressources should not be empty if there are none, that's one thing that immediately jumps out.

What things are under Ressources? Links to documentation and homepages, so that's nothing important that should be absolutely required IMHO. Apps can be so easy to install and use that they simply don't require any documentation. 

Another thing that is probably more important is an issue tracker. Our current default for that is to just send people to the forums if no issue tracker is provided (check the discussion part on https://apps.nextcloud.com/apps/activitylog)

**Comment by MariusBluem** [comment]
> What things are under Ressources? Links to documentation and homepages, so that's nothing important that should be absolutely required IMHO. Apps can be so easy to install and use that they simply don't require any documentation.

Yes... but a an app without repository and developer contact details 😕

**Comment by BernhardPosselt** [comment]
Yeah, I'm undecided if we absolutely want/need information for issue trackers. Would like to hear more opinions on this :)

@MorrisJobke @ChristophWurst @LukasReschke @nickvergessen @adsworth

**Comment by nickvergessen** [comment]
I would say "fine by me", maybe show it as an info to the uploader, that website and issue tracker are missing and that those are good to have, for people reporting bugs.

**Comment by BernhardPosselt** [comment]
You could probably argue: if you do not want to provide support, then keep the app to yourself and dont upload it for others to use. However if you upload it for others to use, we want the experience to be good so you should care about bug reports (or at least collect them somewhere so others can fix them)

**Comment by MorrisJobke** [comment]
> You could probably argue: if you do not want to provide support, then keep the app to yourself and dont upload it for others to use. However if you upload it for others to use, we want the experience to be good so you should care about bug reports (or at least collect them somewhere so others can fix them)

Isn't the comment feature of the App Store enough for communication with the author? I would think so. If the author doesn't provide anything this is fine. At least there are comments below the app itself in the App Store, where feedback can be given. And if the app is that bad, it will get a bad rating.

**Comment by BernhardPosselt** [comment]
The store was specifically designed to avoid comments and just go for something like ratings/reviews: you can post a review once for an app that's it. Everything else leads to bug reports or feature requests like on the old app store.

So if you don't add anything people will get redirected to the forums right now
