### ISSUE TITLE
Let me comment in multiple languages

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/appstore#440]
If i want to get attention in the comments, I do not know in which language to write a comment ... 😢
...or show all comments and don't longer make this distinction - the community is not that large 😅 

cc @nextcloud/appstore

**Comment by BernhardPosselt** [comment]
That's a duplicate, sorry on mobile ;)

**Comment by BernhardPosselt** [comment]
https://github.com/nextcloud/appstore/pull/433
