### ISSUE TITLE
[Feature request]: New Tab All Apps

### ISSUE THREAD

**Issue by EasyPeasy1** [nextcloud/appstore#447]
Hi

do you already thought about a section where you can see all apps?
That would be very helpful if someone would like to find an app over the search bar.

**Comment by BernhardPosselt** [comment]
Click on All Apps https://apps.nextcloud.com/

**Comment by EasyPeasy1** [comment]
You dont see all apps in your nextlcoud instance 

![image](https://cloud.githubusercontent.com/assets/24621703/24035777/36b604d8-0af7-11e7-9765-c09a18ba2b9c.png)

**Comment by BernhardPosselt** [comment]
Ah, this repo is only apps.nextcloud.com and there's already a ticket open for the server

**Comment by EasyPeasy1** [comment]
Ah, ok! 👍 Thanks
