### ISSUE TITLE
Not connecting to App Store ?

### ISSUE THREAD

**Issue by poisony** [nextcloud/appstore#457]
## Details

* Browser and browser version:
All browsers

## Steps to reproduce

1. Fresh install of Nextcloud 11.0.2
2. Change datadirectory to another
3.  Open Apps-page. 

All apps are loading but it does not get connected to the App Store. Only "Enabled" and "Not Enabled" apps showing up.

Can't find any errors. Does this have to do with me changing the data-directory? How do I get this to work again?

**Comment by BernhardPosselt** [comment]
You are in the wrong repo, this is a server issue ;)

**Comment by poisony** [comment]
Oh damn, sorry...
