### ISSUE TITLE
navigations validation missing

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/appstore#463]
info.navigations 1..0 
navigations.navigation 1..n

navigation.id 1..1 (string)
navigation.name 1..1 (string)
navigation.route 1..1 (string)
navigation.icon 0..1 (string)
navigation.order 0..1 (int)
navigation.type 0..1 `link|settings`

Sample: https://github.com/nextcloud/server/blob/e0b040d6235e7f8f8e5869e56a9bda1bf346cafd/apps/files/appinfo/info.xml#L58-L64
```xml
	<navigations>
		<navigation>
			<name>Files</name>
			<route>files.view.index</route>
			<order>0</order>
		</navigation>
	</navigations>
```

PR on server: https://github.com/nextcloud/server/pull/4077

**Comment by BernhardPosselt** [comment]
Oh, finally \o/
