### ISSUE TITLE
Adjust design to fit Nextcloud.com

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#468]
Our current design is pretty basic and is basically just a very lightly styled bootstrap. Ideally the store looks similar to Nextcloud.com which looks fantastic.

I've tried to adapt Nextcloud.com's header but I'm struggling a bit with making the content look nice with all the app previews and the content. 

I'd also like to get rid of our current style files and rather than override bootstrap styles make use of less configuration (maybe through https://github.com/bline/bootstrap-webpack ?) 

As for CSS preprocessor technologies: I'd like to avoid LESS/SASS and go with native bleeding edge CSS. If we need mixins or CSS 4 features I'd tend towards PostCSS but I'm unsure if we need it at all. Ideally all of our CSS is separated so that we maybe have one common CSS file for all pages and one for each page.

**Comment by BernhardPosselt** [comment]
@Espina2 since you did the Nextcloud.com design, are you interested in creating the mockups?

**Comment by Espina2** [comment]
Sure, just ping me again in the next week. @BernhardPosselt

**Comment by MariusBluem** [comment]
ping @Espina2 😜😜

**Comment by Espina2** [comment]
@BernhardPosselt any way that I can have your help for first define a basic styleguide? 

I will love to have one source for all major platforms, in make a way to not repeat ourselfs in any new platform. 

For example we are going to use styles in the Header, Footer and Typography why not have a repo with all of that so we just need to add class to the elements?

**Comment by BernhardPosselt** [comment]
Style guide is a good idea, even better is a linter that enforces it (for code related things).

 But good idea, just do it in small steps so we can quickly replace small things :)

**Comment by Espina2** [comment]
So we can start by the header. When do you have time for start?

**Comment by BernhardPosselt** [comment]
You can start right now :) I probably have time in the evening

**Comment by BernhardPosselt** [comment]
I'm done with work for today. Do you need any specifics? Maybe talk on IRC?

**Comment by Espina2** [comment]
@BernhardPosselt 
I didn't use IRC, do you have skype?

**Comment by BernhardPosselt** [comment]
No, and Skype seems to have issues when I try to create a new account :/

**Comment by BernhardPosselt** [comment]
Simply go to https://webchat.freenode.net/ and enter
* Nick: your nick
* Channels: #nextcloud-dev

My nick is the same as on GitHub

**Comment by BernhardPosselt** [comment]
repo is up https://github.com/nextcloud/toolkit

**Comment by jancborchardt** [comment]
This was fixed now with much thanks to @bigcat88 @andrey18106! :) https://github.com/nextcloud/appstore/pull/1202
