### ISSUE TITLE
Contacts menu provider info.xml registration

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/appstore#476]
```
	<contactsmenu>
		<provider>OCA\Spreed\ContactsMenu\Providers\CallProvider</provider>
	</contactsmenu>
```

contactsmenu: 0..1
provider: 0..1 (may be expanded to 0..n in the future, but the current code is 0..1)
Provider implements: `OCP\Contacts\ContactsMenu\IProvider`

For NC 12

**Comment by BernhardPosselt** [comment]
Thanks! Will do this this evening I guess :)

**Comment by LukasReschke** [comment]
Deployed.
