### ISSUE TITLE
Support for browsers without (full) ECMAScript 6 support?

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/appstore#493]
Palemoon and Internet Explorer (and surely a few others too) don't (fully) support ECMAScript 6, so a few portions of the Nextcloud app store pages don't work.

## Details

* Browser and browser version: Palemoon 27, Internet Explorer 11

## JavaScript Console Output

`SyntaxError: class is a reserved identifier        detail.js (line 1, col 58099)`

## Steps to reproduce

1. Go to apps.nextcloud.com and no image is visible for any app in the "All apps" view, only a spinning circle.
2. Open an app link on apps.nextcloud.com in a browser without full ES6 support like Palemoon, Internet Explorer and the description and the comments section are empty, only a spinning circle is visible.

**Comment by BernhardPosselt** [comment]
See https://github.com/nextcloud/appstore/blob/master/CONTRIBUTING.md#guidelines
