### ISSUE TITLE
App/AppRelease deletion authorizations

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#5]
Currently we've got an app owner and app collaborators. Both are allowed to publish and delete specific apps and their releases. Are we fine with this? If so we can close this ticket :)

@LukasReschke @adsworth @jancborchardt

**Comment by mar1u5** [comment]
I think only owners (and those who are **expressly** allowed to by the owner) should be able to delete an app 😉

**Comment by adsworth** [comment]
I agree with @mar1u5 specially if the app store becomes more than just a place to downlad an app. i.e. it getareas for support, wiki, docs etc.  then in my eyes the collaborators are people helping me manage the workload but I don't want them to mess with my releases.
If we don't plan on extending the appstore do we really need the extra complexity of collaborators?

**Comment by BernhardPosselt** [comment]
Most ownCloud apps like Notes, Calendar, Mail and Contacts are maintained by a bunch of maintainers. It turns out people are unable to release new versions if the guy who created the app on the app store goes on vacation. So collaborators is more like co-maintainers, maybe that's a better word?

As for docs, wikis and support: Docs go into your repo, either in the wiki or a docs folder and support should also be done on Github. It's so much nicer to work with, especially now that you can add an issue template. 

In the past 95% of the comments people posted on the app store were actually bug reports which were very annoying to handle because an app store is a bad bug tracker.

For future features I'm thinking of parsing changelogs and docs from the app archive based on conventions so we get the best of both wolrds :)

**Comment by BernhardPosselt** [comment]
Don't forget the review workflow for pull requests! I think it's an awesome way to create documentation so I'm sure GitHub is the better alternative :)

**Comment by BernhardPosselt** [comment]
Ok, let's rename collaborators to co-maintainers. In that case I think it would be sensible to let co-maintainers release and delete new app releases and adjust the descriptions. An app itself however should only be possible to delete by its original maintainer/owner. Everyone fine with this approach?

**Comment by adsworth** [comment]
Sounds good.
