### ISSUE TITLE
Unable to upload new version

### ISSUE THREAD

**Issue by brantje** [nextcloud/appstore#503]
When i try to upload a new version of my app (Passman) i get an xml error in info.xml.
```
 info.xml did not validate: Element 'type': This element is not expected. Expected is one of ( length,  
  unsigned, notnull, autoincrement, default, comments, primary, precision, scale )., line 493
```
The info xml i supply can be found [here](https://github.com/nextcloud/passman/blob/master/appinfo/info.xml). And the database.xml can be found [here](https://github.com/nextcloud/passman/blob/master/appinfo/database.xml).
According to PHPStorm, and xml validators the both xmls are valid.

**Comment by BernhardPosselt** [comment]
Fixed in https://github.com/nextcloud/appstore/pull/491 but not yet deployed. The culprit is your database.xml

**Comment by brantje** [comment]
Thanks. Fixed it and that solved the problem. Who came up that the elements needs to be in a specific order?

**Comment by BernhardPosselt** [comment]
The parser in core.
