### ISSUE TITLE
Kill nightly versions of apps, if a newer/same version is stable

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/appstore#504]
![img_0461](https://user-images.githubusercontent.com/19711361/28752861-a629e734-7529-11e7-9160-5e3dbe18c1c4.PNG)
Does not make sense to show them 🙈 @BernhardPosselt

**Comment by brantje** [comment]
I agree having the same with my app.
![image](https://user-images.githubusercontent.com/2758767/28752909-82b4374a-752a-11e7-905e-3fc98d1f9aea.png)

**Comment by BernhardPosselt** [comment]
You can do that on your own ;)

Nightlies are daily builds. Makes no sense to publish them if you don't build them daily

**Comment by BernhardPosselt** [comment]
Tldr: either publish them regularly or delete them

**Comment by BernhardPosselt** [comment]
BTW, you most likely are interested in https://github.com/nextcloud/appstore/issues/355 which is about displaying stable/pre-release/nightlies in separate sections (thinking of tabs). This will not display nighties at all when you hit the app page.
