### ISSUE TITLE
[developers doc] github archive issue

### ISSUE THREAD

**Issue by ilyash** [nextcloud/appstore#506]
`docs/developer.rst` states that

> Archives are typically created automatically for you. If you require compilation or other transformations like minification, you should upload a pre-built archive to the appropriate releases page

and

> The archive most only contain one top level folder consisting of lower case ASCII characters and underscores

When GitHub creates archives automatically, the top level folder in that archive is not named APP_ID but APP_ID-version.

I suggest two alternatives:

- If it's supported, update the second chunk of documentation to say that APP_ID-version folder is OK too
- If not, update the first chunk, stating that uploading is required anyway to conform to the required layout.

**Comment by BernhardPosselt** [comment]
Source archives on github won't work, that's why you upload a release archive. Apart from that our hands are tied because nextcloud expects that folder structure.

**Comment by BernhardPosselt** [comment]
So please create a pull request that updates the first paragraph ;)

**Comment by ilyash** [comment]
https://github.com/nextcloud/appstore/pull/507
