### ISSUE TITLE
Newly generated app doesn't build

### ISSUE THREAD

**Issue by bakkegaard** [nextcloud/appstore#516]
## Steps to reproduce

1. Go to apps.nextcloud.com and generate a new app 
2. Push the files to Github
3. Add the repository to Travis
Expected behavior: the app build is successful
Reality: the app doesn't build.
[example](https://github.com/bakkegaard/cookbook)

**Comment by BernhardPosselt** [comment]
This should be fixed on the latest master. Can you try to reproduce it locally? Check http://nextcloudappstore.readthedocs.io/en/latest/devinstall.html for setup instructions

**Comment by bakkegaard** [comment]
Still doesn't work, [Travis](https://travis-ci.org/bakkegaard/cookbook)

**Comment by BernhardPosselt** [comment]
The issue is that your app is cloned from github under a different foldername than your app id. Your repo is called "cookbook" and your info.xml uses testapp: https://github.com/bakkegaard/cookbook/blob/master/appinfo/info.xml#L4

Since travis does not rename your folder, it tries to move testapp to apps/ which ofc does not exist because the cloned folder is called cookbook. I don't think we can do anything for you here, you need to adjust this in your travis.yml

**Comment by bakkegaard** [comment]
Ups, my mistake. Fixed that and it still doesn't seem to work.

**Comment by BernhardPosselt** [comment]
https://github.com/bakkegaard/cookbook/blob/master/tests/Unit/Controller/PageControllerTest.php needs a 

```php
use OCA\Cookbook\Controller\PageController
```

below the namespace. Can you try that?

**Comment by BernhardPosselt** [comment]
If that's the fix btw, we need to add 

```php
use OCA\{{ app.namespace }}\Controller\PageController;
```

here: https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/scaffolding/app-templates/12/app/tests/Unit/Controller/PageControllerTest.php#L8

**Comment by bakkegaard** [comment]
Cool, that actually fixed it for 1 and 3, now it's only 2 and 4 that has errors.

**Comment by BernhardPosselt** [comment]
Issue for https://travis-ci.org/bakkegaard/cookbook/jobs/269572594 is that Nextcloud doesn't like the latest phpunit version https://github.com/nextcloud/server/issues/5235 

Issue for https://travis-ci.org/bakkegaard/cookbook/jobs/269572596 is that you cant install mariadb in a container environment. Probably need to match the changes in https://github.com/nextcloud/app-tutorial/blob/master/.travis.yml#L61 with our local version: https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/scaffolding/app-templates/12/app/.travis.yml

Can you try to use the app-tutorial travis file and if it works for you file a pull request?

**Comment by BernhardPosselt** [comment]
PS: the temp fix for the phpunit issue is to just install it with composer: https://github.com/nextcloud/app-tutorial/blob/master/composer.json then use composer to run the tests https://github.com/nextcloud/app-tutorial/blob/master/Makefile#L79

**Comment by BernhardPosselt** [comment]
Ok, will check this later on. Can you create a pull request with the test fix?

**Comment by bakkegaard** [comment]
Thanks. Sure thing.

**Comment by bakkegaard** [comment]
#519 fixed this problem
