### ISSUE TITLE
Info.xml updates are not recognized for documentation section

### ISSUE THREAD

**Issue by janis91** [nextcloud/appstore#518]
## Details

If I as an app developer update the documentation section of my app with a new version (for example the <user> documentation or the website, because the domain changes or something similar, the new version of the app doesn't update the entries on the app's appstore page. This is not intended like that I guess.

Source: https://github.com/janis91/ocr/issues/120

Maybe it is necessary to update this kind of information every new push of a release, because it might change some links.

**Comment by BernhardPosselt** [comment]
Should actually update just fine, will investigate

**Comment by BernhardPosselt** [comment]
Can you link me two archives, one without and one with the changes? Maybe we can simply add that to a test suite

**Comment by BernhardPosselt** [comment]
FYI: documentation links are persisted on the App model and not the AppRelease. App is only updated if an uploaded release is newer or equal to the current version. https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/api/v1/release/importer.py#L268

**Comment by janis91** [comment]
Ok, I see the reason. It's caused by the nightly version I uploaded. I thought this would also work. But nightlies are not used to update the app model. That's ok for me. I will close the ticket and update the app as fast I have a stable version available. Thanks for investigating!

**Comment by BernhardPosselt** [comment]
Yes the idea behind that is that you don't want to display nightly changes and possible instructions to people that simply download the stable version. There's a ticket called channels where one could think about rendering the nightly page as well when a user selects the nightly channel
