### ISSUE TITLE
Show categories in the UI

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/appstore#528]
Ref https://github.com/nextcloud/server/issues/6868

The categories from info.xml should be displayed in the app store UI of an app:
https://apps.nextcloud.com/apps/admin_notifications

The people know in which category the app is displayed on the server

**Comment by tobiasKaminsky** [comment]
:+1: 
Especially as there is no search in apps on server, one would have to go through all categories to find the desired app…
