### ISSUE TITLE
show if 'official' or not

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/appstore#531]
Most app stores show who the vendor is for an app and if there is support or such.

We could at least show if an app is official, signifying Nextcloud GmbH support. We'd have to think about a label for apps supported by other companies, though (like Collabora).

Another option is to put 'Nextcloud GmbH' behind apps done by employees but many of them are done on 'personal' title and aren't supported. Even the 'official' tag doesn't overlap 100% with what we support for customers.

Thoughts?

**Comment by jospoortvliet** [comment]
A possible solution is to have a 'supported' tag and a 'company' tag. Then Nextcloud GmbH's or Collabora's tag can be given to some apps, the supported to others...

**Comment by BernhardPosselt** [comment]
What about simply stating that it's officially supported in the app description? Asking because I can't think of a nice solution right now.

**Comment by mathiasconradt** [comment]
@BernhardPosselt Do you mean technically or from a layout/design perspective?

I think it would be good to have the info already in the overview, not only on the detail pages. If there would be a filter on the left hand side as well (like the Google Chrome store), this would also be nice.

Two examples I found elsewhere, which I think are quite good:

![screenshot from 2017-11-08 22-42-19](https://user-images.githubusercontent.com/295122/32820947-3c100426-c9d1-11e7-86d6-c1115c379c37.png)
![screenshot from 2017-11-08 22-42-00](https://user-images.githubusercontent.com/295122/32820948-3c415abc-c9d1-11e7-9e53-956a680b520a.png)

**Comment by BernhardPosselt** [comment]
Technical solution. The question is how you make it exensible and usable enough. Maybe a tag in the info.xml which reads:

```xml
<support>commercial</support>
```

or 

```xml
<support>community<support>
```

which can be reused for app devs to also signal commercial support? No idea :)

**Comment by wiswedel** [comment]
"Official" Tags are available now. However, how are they assigned? @jospoortvliet
