### ISSUE TITLE
API publish "JSON parse error"

### ISSUE THREAD

**Issue by Rello** [nextcloud/appstore#533]
Hello,
I am trying to push via the API but cant get it to work for ages:
I am constructing everything in bash.

The sending information from curl seems to be correct:
```
0065: Authorization: Token 74 ... 48
00a4: Content-Type: application/json; charset=utf8
00d2: Content-Length: 827
00e7: => Send data, 827 bytes (0x33b)
0000: {"download":"https://github.com/Rello/audioplayer/releases/downl
0040: oad/2.2.1/audioplayer-2.2.1.tar.gz", "signature": "JE ... sM=", nightly: False}
== Info: upload completely sent off: 827 out of 827 bytes
```
but then a 
```
0000: {"detail":"JSON parse error - Invalid control character at: line
0040:  1 column 180 (char 179)"}
```

my curl is
                `curl --trace-ascii /dev/stdout -X POST -H "Authorization: Token ${token}" https://apps.nextcloud.com/api/v1/apps/releases -H "Content-Type: application/json; charset=utf8" -d '{"download":"'"$gitlink"'", "signature": "'"$signature"'", nightly: False}'`

any hint?

**Comment by BernhardPosselt** [comment]
Lowercase your false. Next time simply validate your Json ;)

**Comment by Rello** [comment]
nope :-(

```
0000: {"download":"https://github.com/Rello/audioplayer/releases/downl
0040: oad/2.2.1/audioplayer-2.2.1.tar.gz", "signature": "JE...sM=", "nightly": "false"}
```
still same?!
any other suggestion?

**Comment by BernhardPosselt** [comment]
Now you've added "" to your false

**Comment by BernhardPosselt** [comment]
Also there seems to be a line break in your URL, remove that

**Comment by Rello** [comment]
also without the "" around false, it does not work.

```
{"download":"https://github.com/Rello/audioplayer/releases/download/2.2.1/audioplayer-2.2.1.tar.gz", "signature": "JE...wsM=", "nightly": false}
```

the message above is only the output of the `--trace-ascii /dev/stdout`. no line break in the url.
the connection itself seems to be fine anyway `Connected to apps.nextcloud.com (88.198.160.138) port 443 (#0)`

Anyone actually using the API in bash/curl?

another finding:
if I remove the signature, I get a "Signature is invalid: Incorrect padding"
can there be a character issue with the signature? in the browser it works fine...

**Comment by BernhardPosselt** [comment]
Incorrect padding just means that your signature is too short. Can you paste your exact command?

**Comment by Rello** [comment]
the incorrect padding was just a test on what happens if I remove the signature.

```
signature=$(openssl dgst -sha512 -sign /home/admin/owncloud-dev/keys_nextcloud/audioplayer.key audioplayer-${version}.tar.gz | openssl base64)
gitlink='https://github.com/Rello/audioplayer/releases/download/'${version}'/audioplayer-'${version}'.tar.gz'
token='74...48'

curl --trace-ascii /dev/stdout -X POST -H "Authorization: Token ${token}" "https://apps.nextcloud.com/api/v1/apps/releases" -H "Content-Type: application/json; charset=utf8" -d '{"download": "'"$gitlink"'", "signature": "'"$signature"'", "nightly": false}'
```

**Comment by BernhardPosselt** [comment]
Are you sure that "'" is correct? Try this stuff in something other than bash please, there are too many pitfalls

**Comment by BernhardPosselt** [comment]
Closing this btw. My guess is that this is a script issue. Take a look at https://github.com/ChristophWurst/krankerl/ which works just fine with the current api

**Comment by Rello** [comment]
Just an additional info on the working solution for me: I needed to provide the content as "file"

```
 curl --trace-ascii /dev/stdout -X POST -H "Authorization: Token ${token}" \
"https://apps.nextcloud.com/api/v1/apps/releases" \
-H "Content-Type: application/json; charset=utf8" \
-d @<(cat <<EOF
{
"download": "$gitlink",
"signature": "$signature",
"nightly": false
}
EOF
)
```
