### ISSUE TITLE
Request: allow Apps to be listed under multiple categories

### ISSUE THREAD

**Issue by sunjam** [nextcloud/appstore#535]
Thanks for your great work!  Please allow Apps to be listed under multiple categories.  Everything is currently assigned only one category and most apps are not easy to find without searching.  Also, far too many apps stuck in the *Tools* category.  *Tools* feels like an *Unsorted* category for the online app store.
    
Example: Keeweb could possibly fit under Security, Integration and Organization... but it currently is only visible within the Tools category at the very bottom of the app categories.
    
UnSplash could be listed under Customization rather than just Tools.
    
Thanks!

**Comment by BernhardPosselt** [comment]
Already implemented ;) Ask the app's maintainers

**Comment by sunjam** [comment]
Will do.  Thank you!
