### ISSUE TITLE
Request: Add an emblem or visual mark to Apps requiring additional setup outside of the Appstore

### ISSUE THREAD

**Issue by sunjam** [nextcloud/appstore#536]
Please add some symbol, emblem or visual mark for Apps that require additional, external administration or "Advanced Setup" outside of the Nextcloud appstore.  This will remind administrators that certain apps will not work by simply clicking enable.
    
Just a few examples:    
ocDownloader requires aria2 and youtube-dl packages be installed and properly configured.
Nextant requires Solr.
Sia requires a Sia package be installed and customized.

**Comment by BernhardPosselt** [comment]
The developer can add that using the **command** tag in the **dependencies** tag. See http://nextcloudappstore.readthedocs.io/en/latest/developer.html#info-xml for more information

That way the installer will tell you what is missing
