### ISSUE TITLE
Prevent apps without releases from appearing on the search page

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/appstore#540]
I know this is a rare / special case but if you create a new app and don´t upload a release you are presented with the app page with nearly all information missing. Would be nice to have a 404 page or some kind of message pointing out that there is no release / info yet.

Example: https://apps.nextcloud.com/apps/mindmaps

Ref https://github.com/splitt3r/mindmaps/issues/27

**Comment by BernhardPosselt** [comment]
File this in nextcloud/server please.

**Comment by splitt3r** [comment]
Why?

**Comment by BernhardPosselt** [comment]
Apps without releases are filtered from the app store https://apps.nextcloud.com/

You probably were redirected to it from inside your Nextcloud, correct?

**Comment by splitt3r** [comment]
Nope. I´m the creator of the app and already added the link to my GH repo (see referenced GH issue). Even if it´s already filtered some hint on the page itself would be nice.

**Comment by BernhardPosselt** [comment]
How should a user find your page?

**Comment by BernhardPosselt** [comment]
Ah, it's found when searching for it.

**Comment by splitt3r** [comment]
No it´s not ^^. But while developing i already linked it in the README.md https://github.com/splitt3r/mindmaps

**Comment by BernhardPosselt** [comment]
Well, that's your choice :)

See it as a neat way to preview your app page then ;)

**Comment by splitt3r** [comment]
Ok  :joy:
