### ISSUE TITLE
Notify users via email after password was changed

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/appstore#546]
To notify users when they forgot to log out somewhere and someone else took over their account.

**Comment by BernhardPosselt** [comment]
Can be solved by adding another line here https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/user/signals.py#L32 

Sending mails to a user is documented here: https://docs.djangoproject.com/en/2.0/topics/email/

**Comment by mario** [comment]
This looks done so closing.
