### ISSUE TITLE
Request: require all apps include a screenshot in app store

### ISSUE THREAD

**Issue by sunjam** [nextcloud/appstore#549]
I humbly request all apps in the appstore be required to post a screenshot or gif image to be listed.  Several apps that have been around since the beginning have no screenshot to show you what they actually do.
    
It just feels like this logo should not be a common sight.
![7c957269-613a-4b29-bca4-6975d54203c7](https://user-images.githubusercontent.com/1787238/36353962-441a742a-1482-11e8-8454-1f29491d44aa.png)

**Comment by BernhardPosselt** [comment]
What kind screenshot do you expect from a purely backend app without frontend?

**Comment by sunjam** [comment]
It would be helpful to add an image or gif giving reference to what the backend app actually adds, changes, or replaces.
![3cfc3a39-9d97-471e-8f8e-89452d2d8c8d](https://user-images.githubusercontent.com/1787238/36488373-20710da6-16d8-11e8-82f5-fe50631a1e45.jpeg)
    
Example is showing a gif image of shifting css code for the _Custom CSS app_, or re-arranging icons in  _App Order_.

**Comment by BernhardPosselt** [comment]
File that issue in the app order issue tracker then. There are apps that add nothing with a UI so a screenshot is impossible.
