### ISSUE TITLE
Add changelog like Google Playstore do it for their apps

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/appstore#555]
Everytime I get a notification which says only there is a new app online in the appstore. I think every user dont want -like me- to open Github first to search for the changelog to see whats new. I  like it how it is in the Playstore on updates, that tells the user whats new. I´m happy about it, even when there stand "little improvements".

When the user sees directly the changelog we get theese advantages:

- The user can directly see whats new and where the improvements are
- The user can test direclty new improvements to report them early. No feedback needed by his own cloudusers.
- The user can decide easilier if he needs the update or not.
- The user can see the necessities to update when the update is just an improvement or a security fix.

Cheers ;)

**Comment by BernhardPosselt** [comment]
Please file this in nextcloud/server ;)

**Comment by BernhardPosselt** [comment]
You can view changelogs here https://apps.nextcloud.com/apps/news/releases?platform=13#13

**Comment by xXSTrikeXx** [comment]
@BernhardPosselt This is related to the NC server version and not the the special app versions. And how do you come to this link? There should be an improvement for UX.
When I want to update an App I go to the app list as admin in my nextcloud instance. There I can open the link to the app in the app store. But there I can´t actually see the changelog of an app.

**Comment by BernhardPosselt** [comment]
First paragraph here: https://github.com/nextcloud/appstore#nextcloud-app-store and here  https://github.com/nextcloud/appstore/blob/master/CONTRIBUTING.md#guidelines ;)

**Comment by xXSTrikeXx** [comment]
@BernhardPosselt Regarding to your PR #353 the changelog isn´t even avaible on your app news. You just link to it in your description and you are the only one who links to a github page. Why couldn´t this directly in the store? To be stamped by you and referring to other issues, where you tell thats a server issue (would be nice to see it in the server, too. But most important it should be seen also on the appstore). You don´t explain anyway how to reach your first link which is also regarded only to server versions.

**Comment by BernhardPosselt** [comment]
You are mixing up the store and the nextcloud store integration.

**Comment by BernhardPosselt** [comment]
The stuff you view Inside your Nextcloud instance is provided by Nextcloud (PHP). The stuff that you see on apps.nextcloud.com is a separate server in Python

**Comment by BernhardPosselt** [comment]
The changelog on apps.nextcloud.com is parsed from a CHANGELOG.md (if you provide one) and then displayed on the apps releases page fyi.

**Comment by xXSTrikeXx** [comment]
@BernhardPosselt nope:
https://github.com/nextcloud/appstore
First line:
 🏪 App Store for Nextcloud https://apps.nextcloud.com

How i said: Would be also nice to see it in my server instance, but most important should be to display it in the store on each app:
https://apps.nextcloud.com

As I say you are only one of a few developers who is linking this in the description:
https://apps.nextcloud.com/apps/news
<details><summary>Quotation</summary>

Before you update to a new version, check the changelog to avoid surprises.
</details>

**Comment by BernhardPosselt** [comment]
> How i said: Would be also nice to see it in my server instance, but most important should be to display it in the store on each app:

I dont really know what you mean

**Comment by xXSTrikeXx** [comment]
Ah ok haven´t read your last post :D 
But on your app it isnt also displayed. And you are providing a changelog.md

**Comment by BernhardPosselt** [comment]
What do you mean by on my app it's not displayed`

**Comment by BernhardPosselt** [comment]
Ah I see, you want a changelog on the app's detail page as well (below the description) and are not satisfied with only viewing it on the releases page.

I don't think that's a real issue here since people don't update from the store directly but use the built in integration.

**Comment by xXSTrikeXx** [comment]
But people use the link to the app store to get to the github page with the changelog to finally see it. :)
That would be a better ux :)

**Comment by BernhardPosselt** [comment]
They wouldn't need to use it if nextcloud actually displayed the changes ;)

Nextcloud could display all changes up to the latest version, whereas in the web ui that's not really possible without you entering your current version. Only having a changelog for the latest release is kinda useless.

**Comment by xXSTrikeXx** [comment]
Well, when you stay all apps up to date, then is only the latest changelog relevant. This could be a good function to see, if the app is still under developement and work is in progress 😃
