### ISSUE TITLE
Version 13 option missing in app skeleton generator

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/appstore#556]
The app skeleton generator at
https://apps.nextcloud.com/developer/apps/generate
only shows version 11, 12 as options for the NC version.
Need to add 13.

**Comment by BernhardPosselt** [comment]
Already implemented, needs a deployment @MorrisJobke

**Comment by MorrisJobke** [comment]
On my list

**Comment by MorrisJobke** [comment]
Done.
