### ISSUE TITLE
Listing App Dependencies

### ISSUE THREAD

**Issue by juliusstoerrle** [nextcloud/appstore#559]
It would be great if the we could list the dependencies of an app on the app page.
Right now I would like to upgrade to PHP 7.2, but I don't know if all my apps support this. As developers can already list their dependencies in the app metadata (http://nextcloudappstore.readthedocs.io/en/latest/developer.html#info-xml) I thought this might be a simple thing to embed maybe below the release table.

Related To: https://github.com/nextcloud/appstore/issues/536

**Comment by BernhardPosselt** [comment]
>  but I don't know if all my apps support this

See https://apps.nextcloud.com/apps/caniupdate

App requirements are on the releases page and usually uninteresting. You will see all info on your nextcloud server page when you install apps (in case you miss deps).
