### ISSUE TITLE
Also list releases for minor server versions

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/appstore#560]
Currently, the list of releases only shows app releases for major versions like 12.0.0 and 13.0.0. Apps release for 13.0.1 are hidden, like for example the latest Mail nightly: https://apps.nextcloud.com/apps/mail

Note that the json API contains the release, so it's only missing on the web UI.

Also note that there's currently a version comparison bug in server that prevents you from installing apps that require minor or patch releases, see https://github.com/nextcloud/server/pull/9024

**Comment by BernhardPosselt** [comment]
That's because @MorrisJobke probably didn't sync releases yet

**Comment by zorn-v** [comment]
This is because there is no BC (back compatibility) breaks in minor releases I think. I have all releases for NC12 of my app and what ?
Just because of min-ver in `info.xml` and I don't know actually is it working there (but I think it should).

My position - old crap should go in history 😄

**Comment by MorrisJobke** [comment]
Updated and refreshed ;) Also added the update to the release tasks for new server releases to also update the appstore.
