### ISSUE TITLE
Is it possible to get description from README.md like CHANGELOG.md ?

### ISSUE THREAD

**Issue by zorn-v** [nextcloud/appstore#563]
If no `<description>` tag provided by example.
To not doing "hacks" like this https://github.com/zorn-v/nextcloud-social-login/blob/master/release.sh#L26

XML is dead format BTW 😉

**Comment by BernhardPosselt** [comment]
See https://github.com/nextcloud/server/issues/8294

> XML is dead format BTW 

Just because you don't know or use it doesn't mean it's dead ;) If you actually work in software you get in touch with it on a daily basis. Also please refrain from restating this opinion in all of your posts.
