### ISSUE TITLE
REST API Returns 503 or 504

### ISSUE THREAD

**Issue by felixrupp** [nextcloud/appstore#564]
## Details

* Safari 11.1.1 on macOs 10.12.6
* CURL 7.59.0 on mac Os 10.12.6

## JavaScript Console Output

* https://apps.nextcloud.com/api/v1/token: Failed to load resource: the server responded with a status of 503 (Service Unavailable)
* https://apps.nextcloud.com/api/v1/token: Failed to load resource: the server responded with a status of 504 (Gateway Time-out)

## Steps to reproduce

1. Create an account on apps.nextcloud.com and confirm it
2. Go to /account/token/
3. Open JS console and see the errors
4. It’s not possible to get a new API Token or to see my current one

Same thing if I call the REST API directly via CURL.

**Comment by MorrisJobke** [comment]
Should work again.

**Comment by ilovemilk** [comment]
This problem has returned, would be great if you could fix it again.

**Comment by felixrupp** [comment]
I have the same problem again, as described in #564 .
