### ISSUE TITLE
Unable to upload app release

### ISSUE THREAD

**Issue by onny** [nextcloud/appstore#570]
Please provide the following details for error reports from https://apps.nextcloud.com/. Ignore in case of a feature request.

## Details

* Browser and browser version:
I tested it on different browsers (Firefox, Brave, Chromium)

## JavaScript Console Output

If unsure see http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers?answertab=votes#tab-top

## Steps to reproduce

Tried to upload an app release with the download link:
  * https://onny.project-insanity.org/files/radio-0.6.2.tar.gz
and the signature:
```
DDWvEL+qrWuWXvok4WlAd6ogfOGvWEaH46Gzf6ydpWIu0E24y40ACwDMW6QTKUzW
po+TVlkFN/4IFVCQr6DbUkvWMrr83kz3q9qg2s5Mmb+N3+zGEKKzAk8izDyH2I7g
vi8FCJAFd5MqwMau4X4XyyyacyG6vOkRsPwbkVlNXeBm3HhVA4U5EUt7Ne3IzRcT
SdYPnGH+2gf3cklj9Wi/viGk5JleWlo5YjroZhitnf94JXs72tJChGHEuDrFmceL
lbbN2dq1FtyhKGWRuVez5zp417Lpw5/QXAnkAHzj+Rgk8FWCA9lEIxZMrDxfF93y
Mdgoge09JSp0uevELfbgl7na8gCKzRtKohWdatJKzrRhDbdlvnLtpUjEGS3iLZj0
BHSZkWfPAC+uXe0bEStg3zx+Qefis5V5pzfQz4xcKVaitqnwdlddZtuGARtQNATS
CYtLWIwEyrNN0P65g5YxYZuhBSDg8SMaKFBcszXYYL+n+KN3AY00H4D6m7foYJ67
uzIjmbFzZom57OBNHyWxHzgl8vHr9hNK9buppf6eGTvqzMXGiaC2f7k0M83kbyp3
nGbQj+UAV9pw2q8LWbZLoB8fxiDiJyBJOJmbMAwFquT3X6I9IMY3ZAfH36yCVVuU
JL/H3Ay7NV+9p3eWKln1E9IwLe6fyJJDfYFjH6K+TdE=
```
Uploading takes a while but then the loading stops and nothing happens

**Comment by BernhardPosselt** [comment]
@MorrisJobke logs?

**Comment by BernhardPosselt** [comment]
Is this fixed?

**Comment by onny** [comment]
Yes, I was able to upload it. One thing I did was renaming radio-0.6.2.tar.gz to radio.tar.gz. Don't know if this was the problem ...
