### ISSUE TITLE
App store generator does not offer Nextcloud 14

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/appstore#571]
On https://apps.nextcloud.com/developer/apps/generate, the versions listed are only 11, 12, 13.

11 is not supported anymore, and 14 should be there. How do we change that? @nextcloud/appstore

**Comment by BernhardPosselt** [comment]
Create a new symlink here if nothing except the version changed: https://github.com/nextcloud/appstore/tree/master/nextcloudappstore/scaffolding/app-templates

**Comment by jancborchardt** [comment]
@MorrisJobke @juliushaertl @ChristophWurst I assume some of you are more aware of any possible changes?

**Comment by MorrisJobke** [comment]
adding 14: 31b57b7a6
removing 11: b411c70e8

**Comment by MorrisJobke** [comment]
Fixed and deployed.
