### ISSUE TITLE
Unable to upload app release

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/appstore#575]
Please provide the following details for error reports from https://apps.nextcloud.com/. Ignore in case of a feature request.

## Details

* Browser and browser version: Chromium 68

## JavaScript Console Output

If unsure see http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers?answertab=votes#tab-top

```
/api/v1/token:1 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
```

## Steps to reproduce

1. Go to https://apps.nextcloud.com/developer/apps/releases/new
2. Insert URL to tarball: https://github.com/nextcloud/bookmarks/releases/download/v0.12.2/bookmarks-0.12.2.tar.gz
3. Insert signature
4. Click upload

Result: :hourglass_flowing_sand:, then nothing.

**Comment by BernhardPosselt** [comment]
Probably needs some https://stackoverflow.com/questions/35810749/nginx-504-gateway-timeout-error-for-django

**Comment by ilovemilk** [comment]
I also got HTTP error 503 and proxy error when trying to upload a release via CURL.
Seems to be the same issue as #564.

**Comment by felixrupp** [comment]
I have the same problem again #564

**Comment by marcelklehr** [comment]
Mh. I've since been able to upload. Some kind of intermittent problem.

**Comment by blizzz** [comment]
Server config was adjusted a bit and makes it hopefully more reliable. If not, please reopen.
