### ISSUE TITLE
Remove app for certain Nextcloud version?

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/appstore#576]
Hello,

I pushed an app for testing purposes with an increased version number that isn't compatible with Nextcloud 14 yet (https://apps.nextcloud.com/apps/ocdownloader). Is it possible to remove the app for a certain Nextcloud version only (it works with all version below 14)?

**Comment by BernhardPosselt** [comment]
Yes, check the REST api: https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#api-delete-release
