### ISSUE TITLE
Feature Request: Clarify when apps do not support/conflict with each other

### ISSUE THREAD

**Issue by sunjam** [nextcloud/appstore#582]
It would be really useful to clearly and quickly identify when an app either conflicts with, or does not support, another app. Perhaps with a red tag or prominent category.

Example: **Group Folders** does not support **Versions** or **Workflow** or **Retention** or **Encryption**.

Currently this info is only available by digging around through the forums or github issues or as a possible random note in the app description.

**Comment by BernhardPosselt** [comment]
I suppose your issue could be covered by having a better description. Group Folders seem to be an exception to the rule so I don't think a separate mechanism is required.

**Comment by BernhardPosselt** [comment]
Closing this now. Let me know if updating the description worked out for you.

**Comment by MarcelRobitaille** [comment]
What about in the case of forking an app? I want to clearly show that my app is incompatible with the original. I'm not sure if something in the description is enough. According to this issue, installing both causes 💥. I'm not sure how obvious it is for users. https://github.com/MarcelRobitaille/nextcloud_google_synchronization/issues/9.

**Comment by bigcat88** [comment]
Nextcloud server does not provide a way to depend one app on other, or to mark them as conflicted ones.
