### ISSUE TITLE
Greenland translations break build

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#588]
@MorrisJobke see https://travis-ci.org/nextcloud/appstore/jobs/473474945#L921

**Comment by MorrisJobke** [comment]
Fixed in https://github.com/nextcloud/appstore/commit/6264db53243419a4e8dc71e6c62aa537318d6f31#diff-770f5395de02f9a6cecf94a136fdbcb9R557

It was Galician ;)
