### ISSUE TITLE
Page load displays raw code

### ISSUE THREAD

**Issue by AmonBune** [nextcloud/appstore#594]
I'm using NC 15 and when I click on Tasks on the top bar, the page shows some garbled code stuff (they seem like codes from a template engine?) like in the following picture:

![image](https://user-images.githubusercontent.com/15927695/52046146-55447900-2546-11e9-8556-61ecc9ce0d56.png)

It would be nice if this text could be changed to something like "Tasks are being loaded..." or "Loading..." instead of this cryptic stuff.

**Comment by BernhardPosselt** [comment]
Sry, wrong repo.

**Comment by AmonBune** [comment]
> 
> 
> Sry, wrong repo.

Sorry, I posted it into the correct repo now. You can delete this issue.
