### ISSUE TITLE
Skeleton app generator doesn't support Nextcloud 15

### ISSUE THREAD

**Issue by Sasmats** [nextcloud/appstore#598]
Don't know if I am missing something, but I am not able to create a skeleton app for NC 15. The latest possible version is NC 14. Is it possible to update a NC 14 compatible app to be NC 15 compatible?

Thanks in advance

**Comment by BernhardPosselt** [comment]
needs another symlink here I guess https://github.com/nextcloud/appstore/tree/master/nextcloudappstore/scaffolding/app-templates
