### ISSUE TITLE
How to upload an app if somebody registered via GitHub?

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/appstore#60]
I mean we don't have a password there 🙈

**Comment by adsworth** [comment]
I guess that increases the priority for #11.

**Comment by BernhardPosselt** [comment]
Solution is in #70: If a user is registered via GitHub or BitBucket we will create a token which is stored in our database (and can be renewed later on in the user profile).

Through that we can authenticate the user as if his credentials are stored on our server :)

**Comment by BernhardPosselt** [comment]
Closing this as solved
