### ISSUE TITLE
Need to return all apps on >=NC16

### ISSUE THREAD

**Issue by rullzer** [nextcloud/appstore#600]
For https://github.com/nextcloud/server/pull/14578

We to deliver the full app list when on NC 16. No server side filtering as the admin gets the option to force enable the app.

CC: @MorrisJobke @blizzz

**Comment by MorrisJobke** [comment]
I would propose to either

1) add a separate query parameter that returns all apps
or 
2) create a separate API endpoint


@BernhardPosselt

**Comment by ChristophWurst** [comment]
>  2. create a separate API endpoint

I would prefer that

**Comment by rullzer** [comment]
Fine by me.

**Comment by BernhardPosselt** [comment]
GET /api/v1/apps.json 

I suppose

**Comment by MorrisJobke** [comment]
Fix for this is in #601
