### ISSUE TITLE
App store: Outdated screenshot

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/appstore#610]
### Steps to reproduce
1. Open app store
2. Go to category Organization
3. Look for bookmarks app
4. Compare screenshot with up-to-date one https://apps.nextcloud.com/apps/bookmarks

### Expected behaviour
The new screenshot should be displayed.

### Actual behaviour
An old screenshot is being displayed.

### Server configuration

**Nextcloud version:** 15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:**Docker

**Comment by juliushaertl** [comment]
Maybe @blizzz can check if the sync cronjob has issues? https://github.com/nextcloud/usercontent.apps.nextcloud.com/blob/master/sync.php

**Comment by blizzz** [comment]
@marcelklehr it's the correct one now, right? I think this was fixed with a recent maintenance job on that system.

**Comment by marcelklehr** [comment]
@blizzz mmh, nope :/ Compare the above URLs, they're still differing.

**Comment by blizzz** [comment]
@marcelklehr Hm, i don't have the old screenshot appearing. Perhaps it is somehow stuck in cash? Does cleaning it/a hard reload/trying with a different browser show the expected one?

**Comment by marcelklehr** [comment]
I tried with chrome, chromium, firefox and curl. All spit out a screenshot with the old UI.

**Comment by blizzz** [comment]
Baffling :-/

**Comment by mario** [comment]
Works for me. So closing until we have a way to reproduce.

**Comment by marcelklehr** [comment]
Yep, it seems to be fixed now.

**Comment by mario** [comment]
Awesome.
