### ISSUE TITLE
Translations break build

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#622]
@MorrisJobke can you take a look at the translation files that break the build?

**Comment by blizzz** [comment]
Morris isn't available currently.

**Comment by blizzz** [comment]
The problematic part:

```po
#: nextcloudappstore/core/templates/app/detail.html:16
#: nextcloudappstore/core/templates/app/detail.html:17
#, python-format
msgid "Latest %(app_name)s releases"
msgstr "Najnovija izdanja %(app_name)"
```

from

```python
<link rel="alternate" type="application/atom+xml" title="{% blocktrans with app_name=object.name %}Latest {{ app_name }} releases{% endblocktrans %}" href="{% url 'feeds-releases-atom'%}?app={{ object.id }}" />
```

The succeeding languages before the failing test do not have that one translated. 

I don't know whether anything has to be done one the code line (I guess not?) or somewhere with the translation tooling.

**Comment by BernhardPosselt** [comment]
Nah, Transifex doesn't validate your Python format strings to match the requirements. So sometimes users insert invalid placeholders like the one above (which is missing the s at the end of %(app_name))

Valid would be:

    msgstr "Najnovija izdanja %(app_name)s"

**Comment by BernhardPosselt** [comment]
More info here: https://docs.python.org/2/library/stdtypes.html#string-formatting-operations

PS: There are Python 3 docs for this as well, just couldn't find a quick comparison

**Comment by BernhardPosselt** [comment]
The tl;dr: you can use positional syntax:

    "string %s formatting %d" % (string_variable, int_variable)

or use names:

    "string %(name1)s formatting %(name2)d" % {"name1": "string", "name2": 3}

**Comment by nickvergessen** [comment]
Fixed croatian and triggered a sync

**Comment by blizzz** [comment]
thanks for the explanation @BernhardPosselt

**Comment by nickvergessen** [comment]
Checked all other languages, none had a similar mistake on that string.

**Comment by nickvergessen** [comment]
Fixed: https://github.com/nextcloud/appstore/commit/565b74cc4e1e5687dc4fdd512134f7e022c60e1b#diff-ecd8e334b027fef7fc3e84bf3d38af17L737
