### ISSUE TITLE
Uploading contacts.tar.gz triggers "No possible app folder found"

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/appstore#63]
```
➜  /tmp curl -X POST -u admin https://apps.weasel.rocks/api/v1/apps/releases -H "Content-Type: application/json" -d '{"download":"https://github.com/owncloud/contacts/releases/download/v0.0.0.104/contacts.tar.gz"}'
Enter host password for user 'admin':
{"detail":"No possible app folder found. App folder must contain only lowercase ASCII characters or underscores"}%
```

But from what I see the archive should be compliant?

**Comment by LukasReschke** [comment]
Also applies to https://github.com/nextcloud/news/archive/8.8.0.tar.gz so my guess is something with the logic is wrong :)

**Comment by BernhardPosselt** [comment]
Already checking :)

**Comment by BernhardPosselt** [comment]
Issue here is the regex which is matched on 

<class 'list'>: ['contacts/appinfo', 'contacts/appinfo/app.php', 'contacts/appinfo/info.xml', 'contacts/appinfo/routes.php', 'contacts/controller', 'contacts/controller/pagecontroller.php', 'contacts/css', 'contacts/css/public', 'contacts/css/public/style.css', 'contacts/img', 'contacts/img/app.png', 'contacts/img/app.svg', 'contacts/img/favicon-mask.svg', 'contacts/img/favicon-touch.png', 'contacts/img/favicon-touch.svg', 'contacts/img/favicon.ico', 'contacts/img/favicon.png', 'contacts/img/favicon.svg', 'contacts/l10n', 'contacts/l10n/.tx', 'contacts/l10n/.tx/config', 'contacts/l10n/ar.js', 'contacts/l10n/ar.json', 'contacts/l10n/bg_BG.js', 'contacts/l10n/bg_BG.json', 'contacts/l10n/cs_CZ.js', 'contacts/l10n/cs_CZ.json', 'contacts/l10n/da.js', 'contacts/l10n/da.json', 'contacts/l10n/de.js', 'contacts/l10n/de.json', 'contacts/l10n/de_DE.js', 'contacts/l10n/de_DE.json', 'contacts/l10n/el.js', 'contacts/l10n/el.json', 'contacts/l10n/en_GB.js', 'contacts/l10n/en_GB.json', 'contacts/l10n/es.js', 'contacts/l10n/es.json', 'contacts/l10n/et_EE.js', 'contacts/l10n/et_EE.json', 'contacts/l10n/fi_FI.js', 'contacts/l10n/fi_FI.json', 'contacts/l10n/fr.js', 'contacts/l10n/fr.json', 'contacts/l10n/he.js', 'contacts/l10n/he.json', 'contacts/l10n/hu_HU.js', 'contacts/l10n/hu_HU.json', 'contacts/l10n/is.js', 'contacts/l10n/is.json', 'contacts/l10n/it.js', 'contacts/l10n/it.json', 'contacts/l10n/ja.js', 'contacts/l10n/ja.json', 'contacts/l10n/ko.js', 'contacts/l10n/ko.json', 'contacts/l10n/mk.js', 'contacts/l10n/mk.json', 'contacts/l10n/nb_NO.js', 'contacts/l10n/nb_NO.json', 'contacts/l10n/nl.js', 'contacts/l10n/nl.json', 'contacts/l10n/no-php', 'contacts/l10n/oc.js', 'contacts/l10n/oc.json', 'contacts/l10n/pl.js', 'contacts/l10n/pl.json', 'contacts/l10n/pt_BR.js', 'contacts/l10n/pt_BR.json', 'contacts/l10n/pt_PT.js', 'contacts/l10n/pt_PT.json', 'contacts/l10n/ro.js', 'contacts/l10n/ro.json', 'contacts/l10n/ru.js', 'contacts/l10n/ru.json', 'contacts/l10n/sl.js', 'contacts/l10n/sl.json', 'contacts/l10n/sq.js', 'contacts/l10n/sq.json', 'contacts/l10n/sv.js', 'contacts/l10n/sv.json', 'contacts/l10n/th_TH.js', 'contacts/l10n/th_TH.json', 'contacts/l10n/tr.js', 'contacts/l10n/tr.json', 'contacts/l10n/zh_CN.js', 'contacts/l10n/zh_CN.json', 'contacts/l10n/zh_TW.js', 'contacts/l10n/zh_TW.json', 'contacts/templates', 'contacts/templates/addressBook.html', 'contacts/templates/addressBookList.html', 'contacts/templates/avatar.html', 'contacts/templates/contact.html', 'contacts/templates/contactDetails.html', 'contacts/templates/contactImport.html', 'contacts/templates/contactList.html', 'contacts/templates/detailItems', 'contacts/templates/detailItems/adr.html', 'contacts/templates/detailItems/date.html', 'contacts/templates/detailItems/groups.html', 'contacts/templates/detailItems/hidden.html', 'contacts/templates/detailItems/n.html', 'contacts/templates/detailItems/tel.html', 'contacts/templates/detailItems/text.html', 'contacts/templates/detailItems/textarea.html', 'contacts/templates/detailItems/url.html', 'contacts/templates/group.html', 'contacts/templates/groupList.html', 'contacts/templates/main.php', 'contacts/templates/part.settings.php', 'contacts/js/public', 'contacts/js/public/script.js', 'contacts/js/dav/dav.js', 'contacts/js/vendor/angular/angular.js', 'contacts/js/vendor/angular-route/angular-route.js', 'contacts/js/vendor/angular-cache/dist/angular-cache.js', 'contacts/js/vendor/angular-uuid4/angular-uuid4.js', 'contacts/js/vendor/vcard/src/vcard.js', 'contacts/js/vendor/angular-bootstrap/ui-bootstrap.min.js', 'contacts/js/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js', 'contacts/js/vendor/angular-sanitize/angular-sanitize.js', 'contacts/js/vendor/ui-select/dist/select.js', 'contacts/js/vendor/jquery-timepicker/jquery.ui.timepicker.js']

Every element starts with contacts/ however the parser only matches https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/core/api/v1/release/parser.py#L37

In some cases it seems that the folder is there as single name, sometimes not. Will go to bed now ;)

**Comment by BernhardPosselt** [comment]
BTW fix is a bit more complicated since we also need to extract the folder name.
