### ISSUE TITLE
Github deprecation notice

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/appstore#653]
## Details

* Browser and browser version: n/a

## JavaScript Console Output

n/a

## Steps to reproduce

1. Have an Github-authenticated account on apps.nextcloud.com
2. Receive an email from Github

```
Hello there!

On February 4th, 2020 at 03:36 (UTC) your application (Nextcloud Appstore) used an access token (with the User-Agent python-requests/2.22.0) as part of a query parameter to access an endpoint through the GitHub API.

https://api.github.com/user

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

Thanks,
The GitHub Team
```

**Comment by BernhardPosselt** [comment]
Probably requires a Django allauth lib update

**Comment by ChristophWurst** [comment]
I'm also wondering why the app store accesses my account at that time. Is there any kind of background jobs that run at night?

**Comment by BernhardPosselt** [comment]
Hmm, could also be related to the daily import of new nextcloud released

**Comment by mario** [comment]
@BernhardPosselt the daily import seems to be fine:

```
        self.headers = None if self.api_token else {
            'Authorization': 'token %s' % self.api_token
        }
```

Unfortunately AllAuth didn't yet update its code to work with Github properly:

https://github.com/pennersr/django-allauth/blob/88e82021be6b4bc7de0d9dfefc1b23350b982821/allauth/socialaccount/providers/github/views.py

**Comment by mario** [comment]
There is a pending PR: 

https://github.com/pennersr/django-allauth/pull/2458

Let's wait till this is merged and we can update the lib then!

**Comment by mario** [comment]
Merged now, but still waiting for a release.

**Comment by jancborchardt** [comment]
On May 25, 0.42.0 has been released: https://github.com/pennersr/django-allauth/pull/2458#issuecomment-633449301

So we could update the library, right?

**Comment by ChristophWurst** [comment]
That would be https://github.com/nextcloud/appstore/pull/719

**Comment by MorrisJobke** [comment]
Deployed.
