### ISSUE TITLE
Password reset sends outdated reset token

### ISSUE THREAD

**Issue by simonspa** [nextcloud/appstore#659]
When requesting a password reset link from apps.nextcloud.com, the token in the link of the reset e-mail does not work, the website reports:

>  Bad API Token
> 
> The password reset link was invalid, possibly because it has already been used. Please request a new password reset.

When requesting a new password reset, an e-mail with the very same token is sent. In consequence it is impossible to change the password.

## Details

* Firefox 72.0.2

## Steps to reproduce

1. "Forget" your password
2. Request password reset link
3. Receive e-mail and open reset link
4. Observe error, follow suggestion and request new link
5. Receive e-mail with exactly the same token

**Comment by DBJRdev** [comment]
We can confirm your report, same here. No way to log in again once you've forgot your password....

![Bildschirmfoto von 2020-02-20 15-29-38](https://user-images.githubusercontent.com/13522599/74944151-dabaf580-53f5-11ea-9286-e8368fef3cee.png)

**Comment by BernhardPosselt** [comment]
@mario can you check if your customization needs to be updated https://github.com/nextcloud/appstore/pull/618 ?

**Comment by mario** [comment]
@BernhardPosselt sure.

**Comment by SuperSandro2000** [comment]
Just a little bump that this is still a problem.

**Comment by kesselb** [comment]
https://github.com/nextcloud/appstore/blob/e72e1655619b55b848bf5056d63267921ebb27ce/nextcloudappstore/user/forms.py#L100-L102

I don't know django but it seems to me that the generated token is used to generate the password reset url but never saved.

**Comment by mario** [comment]
@kesselb that lines are commented out upstream and weren't changed in the past 10 years. While possible, I'd be surprised if everyone using the lib doesn't have functioning password resets for 10 years :) 

I will take a look though, who knows ... thanks for pointing at it.
