### ISSUE TITLE
Wrong "Password changed" e-mail

### ISSUE THREAD

**Issue by cweiske** [nextcloud/appstore#675]
I just got an e-mail from the appstore, indicating that I changed the password - but I did not do that.

```
Subject: =?utf-8?q?Nextcloud_App-Store_Passwort_ge=C3=A4ndert?=
From: no-reply@nextcloud.com
To: thisisnotreal@cweiske.de
Date: Thu, 2 Apr 2020 20:08:58 +0000
Message-ID: <010201713c82d33a-92035c66-ae3d-45ee-b02f-7713f5612fff-000000@eu-west-1.amazonses.com>
 
Dein App-Store-Passwort wurde geändert. Kontaktiere den Support, wenn Du dies nicht veranlasst hast.
```

I'm the developer of grauphel in case you need my email address. https://apps.nextcloud.com/apps/grauphel

**Comment by mario** [comment]
Could you actually login with your password?

**Comment by cweiske** [comment]
yes.

**Comment by mario** [comment]
That's odd :-/ 

@nextcloud/infrastructure any ideas if we had any mail server problems at the time?

**Comment by MorrisJobke** [comment]
> @nextcloud/infrastructure any ideas if we had any mail server problems at the time?

Not that I'm aware. maybe @blizzz knows something.

**Comment by MorrisJobke** [comment]
I noticed it now as well. When doing a login via username and password I also got this email. @Mario Does this help you in spotting the issue? Maybe the password hash is updated (due to new format or hashing algorithm) and thus causing this to trigger?

**Comment by mario** [comment]
I am not aware in the change of format, but I've looked when this email is sent - it's indeed only on password change. Strange.

**Comment by bigcat88** [comment]
If someone will face the same, please report - until then I will close the issue
