### ISSUE TITLE
Spam in Appstore

### ISSUE THREAD

**Issue by JSoko** [nextcloud/appstore#681]
Now Spam also reaches the appstore...
## Steps to reproduce
Have a look at the new relases in appstore:
https://apps.nextcloud.com/?order_by=last_release&ordering=desc

![spam](https://user-images.githubusercontent.com/5583290/79302106-a4788e80-7eeb-11ea-8892-a2931ebac624.jpg)

**Comment by mario** [comment]
You are right. @blizzz can you remove them?

@karlitschek @jospoortvliet I'm afraid my assumption of getting spam in the Integration category if we don't have any approval process has came true - what do you want to do here?

**Comment by MorrisJobke** [comment]
Talked with @nickvergessen and he cleaned them up for now.

**Comment by nickvergessen** [comment]
Since integrations also block the appid, they should just also require to get a cert and validate the cert on integration registration.

**Comment by karlitschek** [comment]
The whole cert process is a bit complicated for the whole integration idea. Most entries should only be an bit of an explanation text and a link to more information. Is there no other idea?

**Comment by mario** [comment]
I could add the "Pending integrations" part to the admins who would do a one-off approval on initial submit. 

But anyway, there's mail now from @jospoortvliet.

**Comment by MorrisJobke** [comment]
Assigned to @Mario as he is now working on a little approval page in the admin section of the appstore.

**Comment by Valdnet** [comment]
The patch has been added to the project and not released. The last version 4.0.0 is from 10 Nov 2018  :open_mouth:.
Topic raised in the [forum](https://help.nextcloud.com/t/when-the-new-version-of-the-apps-store-for-nextcloud/79420).

**Comment by mario** [comment]
Yea, no releases for a while it looks like. 

I'll close this issue since it was closed / fixed, but feel free to re-open an issue that we should be doing releases.

**Comment by MorrisJobke** [comment]
> The patch has been added to the project and not released. The last version 4.0.0 is from 10 Nov 2018 😮.

As of now we just deploy all changes to master regularly. We haven't done releases lately because there was no demand for "just a version number" we just don't do it. Running master should be fine if someone wants to contribute here.
