### ISSUE TITLE
Show nextcloud 19 releases.

### ISSUE THREAD

**Issue by tacruc** [nextcloud/appstore#699]
Nextcloud 19 is already in beta state. People and tester for apps cannot see or download releases for this version on the web interface.

**Comment by mario** [comment]
It doesn't seem like the app store ever had beta releases though. :-/

**Comment by mario** [comment]
@MorrisJobke might know best? :P

**Comment by MorrisJobke** [comment]
> @MorrisJobke might know best? :P

There is a way to add them via the admin interface -> releases. Let me do that.

**Comment by MorrisJobke** [comment]
I added `19.0.0` as not the current release (because it is not yet released). Now it should also show up for apps.
