### ISSUE TITLE
Problems with registered app integrations not showing up in app store

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/appstore#717]
Hello,

I registered some browser extensions as "integrations" in the App Store, but they neither show up under "Integrations" nor in my registered integrations:

![image](https://user-images.githubusercontent.com/10073629/82728784-e36fe000-9cf2-11ea-828c-043d71766555.png)

![image](https://user-images.githubusercontent.com/10073629/82728820-2af66c00-9cf3-11ea-998a-454b21df8cb0.png)

Interestingly, I can see them in the "Transfer app ownership" page (ocDownloader Webextension for Firefox and Chrome):

![image](https://user-images.githubusercontent.com/10073629/82728752-b6bbc880-9cf2-11ea-94bb-fe0c639d5282.png)

**Comment by mario** [comment]
They were not approved yet - I am still thinking of they should be one listing.

Them showing under transfer apps is a bug though

**Comment by e-alfred** [comment]
Well, then it would be necessary to be able to add multiple links to one integration as well as multiple screenshot URLs and so on.

Maybe a status page for pending reviews would be a good idea to give an overview of what is going on for developers?

**Comment by mario** [comment]
I've added your feedback to https://github.com/nextcloud/appstore/issues/670 - and you are indeed right. In the mean time I'll go ahead and approve your integrations.

Sorry for the delay on this!

**Comment by e-alfred** [comment]
It seems like @jospoortvliet stumbled over another bug after editing one extension so it is now assigned to him. Is there any way to solve this? Or should I register it again?

**Comment by mario** [comment]
I fixed it already :)
