### ISSUE TITLE
apps.nextcloud.com offline

### ISSUE THREAD

**Issue by JSoko** [nextcloud/appstore#735]
apps.nextcloud.com seems to be offline...

https://apps.nextcloud.com

[appstoreFetcher] Warning: Could not connect to appstore: cURL error 28: Connection timed out after 60002 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

GET /settings/apps
from 217.230.xxx.xxx by xxxxxx at 2020-07-28T08:36:46+02:00

**Comment by JSoko** [comment]
Works again...

**Comment by guny74** [comment]
Hello, 

apps.nextcloud.com seems to be offline again ?!

Error on opening during installation (nextcloudpi/docker) and opening the apps menu.

Regards
   Thorsten

**Comment by mygithuber** [comment]
+1

**Comment by joko2020** [comment]
https://status.ws/sites/apps.nextcloud.com/5009813609119744 still down.
what happen ??
