### ISSUE TITLE
Add my third party app (which is not an add-on)

### ISSUE THREAD

**Issue by melroy89** [nextcloud/appstore#756]
Hi,

Is it allowed to add my third party application for Nextcloud to the apps.nextcloud.com? _Note:_ this is a stand-alone application, which is not a Nextcloud add-on per se.

I created a graphical file drop application (written in Python & wxPython), which enables you to easily upload any file you like to the cloud (drag & drop). The application works much faster than when I use my web browser.

My intention was to create a fast, reliable and secure way of uploading (large) files to your Nextcloud instance. Which is basically  a file uploader over WebDav. I can get speeds 2-3x faster than via Firefox.

**Git project repo:** https://gitlab.melroy.org/melroy/nextcloud-file-drop

Screenshot:
![Nextcloud File Drop](https://gitlab.melroy.org/melroy/nextcloud-file-drop/-/raw/master/images/screenshot.png)

I also provide a deb download: [Download the v1.2 of file drop](https://gitlab.melroy.org/melroy/nextcloud-file-drop/uploads/fae820c00126470a7bb37572c8248958/filedrop_1.2_all.deb) (Debian/Ubuntu/Linux Mint distros)

If app-store isn't the place, where could I advertise my application? Since, I think it's really handy. I found it very useful at least.

Thanks!

Regards,
Melroy van den Berg

**Comment by Matthew-Hine** [comment]
Hey, 

I would refer to the documention for this. See [inside this KB for more info](https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/publishing.html)

You can add 3rd party applications to the Appstore now (See #95)

Hope this helps.

**Comment by bigcat88** [comment]
Hello. As last comment mention, currently it is already possible for a long time, and called Integration with button: "Register Integration".
Feel free to write here and we will reopen this issue or create new, if any question still remain.
