### ISSUE TITLE
Outdated links of app

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/appstore#767]
https://apps.nextcloud.com/apps/nextnotes

All links are pointing to `404`.
The project hasn't been updated since **4 years**.

How should we handle this?

**Comment by MorrisJobke** [comment]
No real idea ... maybe delete them on request?

cc @rullzer @blizzz @nickvergessen

**Comment by nickvergessen** [comment]
https://twitter.com/janiskoehr
https://github.com/janis91/

Ask on twitter or send an email?

**Comment by stefan-niedermann** [comment]
Sounds reasonable.
Let's do the short way :wink: 

@janis91 i noticed that all links from the [NextNotes](https://apps.nextcloud.com/apps/nextnotes) app are outdated in the Nextcloud app store. Could you please give us a short update about the status of the project? Is it abandoned / canceled or are just the links outdated?

**Comment by nursoda** [comment]
No reaction in two years → @admins, please delete this app it it's still abandoned. Otherwise close this bug as resolved.
