### ISSUE TITLE
"Ghost" app always showing up on the app store if a Nextcloud release is added

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/appstore#774]
Hello,

everytime a new Nextcloud release is added to the App Store, a strange and very old release of the "Phone Sync" app is added to the App Store automatically:

https://apps.nextcloud.com/apps/ocsms

```
Nextcloud 20 	1.10.1 		All releases
Nextcloud 19 	2.1.8 		All releases
```

There is currently no new release for Nextcloud 20, but version 1.10.1 is added automatically without interaction from the app devlopers. It also happened with Nextcloud 19 before a real release was registered in the App Store by the app developers.

**Comment by e-alfred** [comment]
Same problems happens now with Nextcloud 21.

![image](https://user-images.githubusercontent.com/10073629/102992497-94558c00-451b-11eb-80dd-7bd18f3a98f2.png)

**Comment by SystemKeeper** [comment]
I‘m not experienced with the App Store in any way, but just looking at the versions, 1.10.1 looks to be the last version with no „max-version“ set for NextCloud:

https://github.com/nextcloud/ocsms/commit/8ecf36046259f2af2e30a46b03fcdaf0bab41361

compare to

https://github.com/nextcloud/ocsms/commit/9db19c98bed0794f0a9ab020c4dc5fa54076cd88

So 1.10.1 is the last version valid for 21, from the appstores point of view I‘d guess.

**Comment by nickvergessen** [comment]
Yeah well if there is no maximum, you claim it works with all versions. Same if you upload with maximum 22 right now, it will show as release when we add 22.

Shall I delete 1.10 and all before without a maximum?

**Comment by joshtrichards** [comment]
Seems:

- This isn't really an app store issue at the moment (i.e. it's not a rogue app; just unmaintained and the explanation for this fun mystery makes sense)
- There's some effort to include others in maintenance of the app (e.g. https://github.com/nextcloud/ocsms/issues/352 + others with a bit of recent activity in that repo)
- There's nothing to be done here in this repo at this point

Okay to close here?

**Comment by nickvergessen** [comment]
We could also delete the 1.* release(s) without the max version, because there were releases afterwards.

**Comment by joshtrichards** [comment]
I completely missed that there were *actual* releases after that... :laughing:  

I vote for deleting the 1.* release(s) that lack the max-version (since their overlap seems a no-op anyhow since >NC9 users all have access to >1.13.1). 

Looks like v1.8.2.1 thru  v.1.11.0 lack `max-version`.

- https://github.com/nextcloud/ocsms/blob/v1.8.2.1/appinfo/info.xml
- https://github.com/nextcloud/ocsms/blob/v1.11.0/appinfo/info.xml

Though now I'm confused why v1.11.0 isn't the current "ghost version" in the store. Guess it was just never actually uploaded?

**Comment by nickvergessen** [comment]
1.11.1 is also fixed, so deleted the 2 affected publishings
