### ISSUE TITLE
Comment Guide

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#78]
In the past comments were (ab)used to:
* File bug reports (A LOT)
* Ask for features (A LOT)
* Ask for documentation

These comments neither help people nor users. 

As a developer I want that users post bugs and feature requests on the bug tracker and that users look up setup documentation and FAQ entries before posting comments

As a user I'm interested in what others think about the app, e.g. "I like the app because it has feature XY" or "App seems unmaintained" or "There is an alternative which is better"

I therefore vote for making commenting a bit harder: As a user, after I click on the comment button I should be presented with a set of choices (in my head they are tiles) which ask the user what he wants to write:
* I've got an error/bug/problem: This will be rendered if the app provides an issue tracker Url and will redirect to it
* I want to propose a feature: This will be rendered if the app provides an issue tracker Url and will redirect to it
* I need help to set up the app: This will be present if the app provides an admin documentation link
* I've got a basic question: This will be present if one or more documentation links are present. This will ask the user what kind of question he has and redirect to the appropriate documentation
* I want to share my impressions or provide feedback: This will actually redirect to the actual comment form :D
* I want to contribute code: This will be rendered if the app provides a developer documentation Url and will redirect to it

The choice which redirects to the form should neither be the first nor the last entry and if there are multiple columns should be in the middle or right.

What needs to be done: The app detail view which contains the comment button should be adjusted to redirect to the questionaire. The different links need to be rendered depending on if the saved values are non empty.

**Comment by adsworth** [comment]
Very good idea.

Maybe it would be possible and feasible to submit bug reports via githubs and bitbucket API if the issue tracker of the app is hosted on one of the platforms. 
https://developer.github.com/v3/issues/#create-an-issue
https://confluence.atlassian.com/bitbucket/issues-resource-296095191.html#issuesResource-POSTanewissue
we would have to check up front if the user is also authenticated with the respective service as creating issues doesn't work otherwise.

though that can be pushed way back.

**Comment by BernhardPosselt** [comment]
You probably want issue templates and all the jazz :)

You can also add this to the \<bugs> tag: https://github.com/nextcloud/appstore/issues/new

If a user clicks on that he will be presented with an input form which directly lets him post issues (needs to be logged in ofc).

**Comment by BernhardPosselt** [comment]
Superseeded by #212
