### ISSUE TITLE
App store down since more than a day

### ISSUE THREAD

**Issue by sualko** [nextcloud/appstore#795]
I noticed the first outage 30h ago. According to a [post on help.nextcloud.com](https://help.nextcloud.com/t/appstore-down-unable-to-access-apps-nextcloud-com/106142) it seams to be down from time to time since a few days. It would be nice to have an official Nextcloud reaction to this, so people know what they are dealing with. 

Sorry to bother you with this on the weekend @MorrisJobke @karlitschek

**Comment by cdekkers** [comment]
Same here, many others are having issues as well:

ttps://help.nextcloud.com/t/app-store-is-down/106193/1
https://help.nextcloud.com/t/appstore-down-unable-to-access-apps-nextcloud-com/106142

Perhaps a proper reporting mechanism should be considered, as (at least to me) there appears no real way of notifying the right people of issues such as these.

**Comment by mephpilot** [comment]
I 

> I noticed the first outage 30h ago. According to a [post on help.nextcloud.com](https://help.nextcloud.com/t/appstore-down-unable-to-access-apps-nextcloud-com/106142) it seams to be down from time to time since a few days. It would be nice to have an official Nextcloud reaction to this, so people know what they are dealing with.
> 
> Sorry to bother you with this on the weekend @MorrisJobke @karlitschek

Seems that nobody is taking care of this issue 😩 
I couldn't find any official comunication related to this.🤷🏼‍♂️

**Comment by paulcalabro** [comment]
I think it would really helpful to receive a notification in the UI, much like the ones we receive about new NC releases.

**Comment by mephpilot** [comment]
Here is ok now.

**Comment by cdekkers** [comment]
> Here is ok now.

Issue indeed seems to have been solved, altough I do get the impression that this happens more often based on the replies on the help forum, so my suggestion from earlier still stands:

> Perhaps a proper reporting mechanism should be considered, as (at least to me) there appears to be no real way of notifying the right people of issues such as this.

**Comment by sualko** [comment]
Maybe it would be a good idea to use mirrors like Linux is doing it since decades. Should be simple and could be implemented as app.

The mirror probably only needs to provide `/api/v1/apps.json`and `/api/v1/categories.json`, see #771.

The app should contain a list of mirrors which the user can choose one to use as `appstoreurl`. Mirror providers can't inject malicious code, because all apps are signed, but they could withdraw some apps. Therefore a trust mechanism or an automatic check should be implemented.

Mirrors could be created with a scheduled github action.
