### ISSUE TITLE
App detail page 

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#80]
The app detail page should list the app author, name and description (rendered in markdown) in the appropriate locale, the screenshots, releases and links.

The screenshots should get the most prominent spot and should be shown in a slideshow (non jquery, slim solution preferred. If you don't need JS but only solve it using CSS, even better!)

Vertical layout should be:
* Title
* Gallery
* Description
* Releases page links, one for each platform (Nextcloud 9.0, Nextcloud 9.1) that contains at least one of the app's releases

The authors information should NOT show his email address and should give him just enough space to feel proud but should not steal the focus from the screenshots.

We should also use an icon or a special style to render the featured attribute.

All links like documentation, website, bug tracker etc, should be placed discretely. The old app store does this pretty well, check out https://apps.owncloud.com/content/show.php/Gallery%2B?content=169116

**Comment by janibonnevier** [comment]
Is the idea here to completely ditch the current layout, or just tweak it?

**Comment by BernhardPosselt** [comment]
Ditch mostly.

**Comment by janibonnevier** [comment]
I'm not sure what to do about the Releases tab. Is #79 referring to this tab, or an actual new separate page?

**Comment by BernhardPosselt** [comment]
Releases are a separate ticket.

We don't want a releases tab, we want a list of nextcloud versions that have at least one app release. If you click on one release we should render a list of all releases running on that version where the newest release is on top.

**Comment by janibonnevier** [comment]
And that list should be rendered right there on the app detail page?

**Comment by BernhardPosselt** [comment]
The nextcloud version list, yes, the app version list, no

**Comment by BernhardPosselt** [comment]
I mean we could add two buttons like: download the latest release for this nextcloud version and see all releases for that nextcloud version

**Comment by BernhardPosselt** [comment]
Which makes sense given that you usually want to just download the latest version :)

**Comment by janibonnevier** [comment]
Non-nightly version, right?

**Comment by BernhardPosselt** [comment]
Yes, however we also need to think about how to handle nightly versions. 

Given that they are unstable and potentially insecure and might break your system we should not display them as prominent as the other versions. 

I'll let you think of something ;)
