### ISSUE TITLE
App search

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#82]
As a user you should be able to search apps. The search field should be rendered in the navigation or banner (inline it) and should search app's titles, descriptions and comments. The resulting list should look and work the same as the app list (meaning you can also sort based on various criteria).

The first implementation should be very simple.

**Comment by adsworth** [comment]
Please don't search in the comments. I think that would cause to many false positives. If I search for bookmark then I don't want apps to appear were a user commented "I saved a bookmark" or something similiar. If you want comments searchable then make it optional with a checkbox.
Personally I think I wold only ever want to search the comments of one specific app. I don't see the value of searching the comments of all apps at once.

**Comment by BernhardPosselt** [comment]
Fine by me :) This can be pushed back in case we need some advanced search
