### ISSUE TITLE
unstyled pages after cancelling or completing github login

### ISSUE THREAD

**Issue by blizzz** [nextcloud/appstore#825]
After cancelling login via Github, the landing page appears like:

![Screenshot_20210406_234511](https://user-images.githubusercontent.com/2184312/113783143-98f12980-9733-11eb-84af-e8392ebef632.png)

After completing registering via Github, the landing page looks like:

![Screenshot_20210406_235723](https://user-images.githubusercontent.com/2184312/113783304-d81f7a80-9733-11eb-9b0d-1e255ac7abdf.png)

Actually I am not sure whether this was the case before the allauth update, i suspect it is it.

**Comment by ecsecta** [comment]
The same problem exists with the mails (and form) for the password request procedure.

**Comment by CarlSchwan** [comment]
This is fixed with https://github.com/nextcloud/appstore/pull/642 :)

**Comment by CarlSchwan** [comment]
Fixed and deployed
