### ISSUE TITLE
Recaptcha broken at user registration

### ISSUE THREAD

**Issue by tueksta** [nextcloud/appstore#833]
Please provide the following details for error reports from https://apps.nextcloud.com/. Ignore in case of a feature request.

## Details

* Browser and browser version:

Vivaldi | 3.7.2218.58 (Stable channel) (x86_64)
Revision | c5602492bfee983ae50345020ace09854e38bcf5
OS | macOS Version 10.14.6 (Build 18G8012)
JavaScript | V8 8.9.255.25
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36

## JavaScript Console Output

Refused to frame 'https://google.com/' because it violates the following Content Security Policy directive: "frame-src https://www.google.com/recaptcha/".

## Steps to reproduce

1. Open https://apps.nextcloud.com/signup/  with Vivaldi Browser

<img width="1855" alt="Screenshot 2021-04-22 at 21 49 26" src="https://user-images.githubusercontent.com/22725740/115776920-f8e30380-a3b4-11eb-9b73-71d502cffef5.png">
<img width="535" alt="Screenshot 2021-04-22 at 21 52 19" src="https://user-images.githubusercontent.com/22725740/115776968-07311f80-a3b5-11eb-832e-703d2faa254a.png">

**Comment by blizzz** [comment]
I can reproduce. Google Recaptha shall not be used more though, thus needs a replacement. For now, please use signup through Github.

**Comment by ecsecta** [comment]
I registered via GitHub. How can I change my username now?

**Comment by augustebaum** [comment]
I'm having the same problem. I tried with Opera, Qutebrowser, Chromium, Firefox and Safari.

**Comment by JanVanRoy** [comment]
<img width="598" alt="afbeelding" src="https://user-images.githubusercontent.com/49483576/134527485-b4cb2c88-e685-49a7-bf60-2663b1a00e60.png">

**Comment by FredyKyong** [comment]
Does not work in FF, does not work in Chrome, does not work in Edge. What browser is recommended? Tor?

**Comment by dharmann** [comment]
Sorry but...still no solution nowadays? I don't want to use Github at all, but I wish to develop apps...

**Comment by gitdode** [comment]
Indeed still not working:

`Content Security Policy: The page’s settings blocked the loading of a resource at https://google.com/recaptcha/api2/anchor?ar=1&k=6Le-jiMTAAAAAPaan91cATdIy2hmH-3B3toc3A-R&co=aHR0cHM6Ly9hcHBzLm5leHRjbG91ZC5jb206NDQz&hl=en&v=2W_gRz39xX8G13fM-OdyQPlc&size=normal&cb=g7xvdktnx8xt (“frame-src”)..
`

**Comment by tflidd** [comment]
Can you perhaps fix the Content Security Policy to make it work? There are still errors:
![grafik](https://user-images.githubusercontent.com/8111200/168422722-e6a6e62b-e465-4d7e-aefe-85d0fbf503b9.png)

At least then it is usable and we can wait for a more perfect solution and you have some time to figure out a good replacement. Having registration not working for more than 1 year is not acceptable.

**Comment by nursoda** [comment]
I propose to just switch to https://friendlycaptcha.com/de/ (and fix the CSP) – that would be a quick win until one has time to implement a home brew solution.
