### ISSUE TITLE
Generated applications have an invalid name in Composer 2.0

### ISSUE THREAD

**Issue by srbaker** [nextcloud/appstore#834]
When generating an application from the store, it recommends using a CamelCase name, and puts that as `name` in the `composer.json`

Since Composer 2.0, the `name` field must be all lowercase and numbers, and must contain a vendor part i.e.  `foo/bar` or `nextcloud/tasks`.  The validity regex is `^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$`

(See https://getcomposer.org/doc/04-schema.md#name)

Following the directions for my project FocusFrog generates a `composer.json` containing `"name": "FocusFrog"`.

I am happy to fix this myself and contribute it, but we need to add a field to the generator that represents "vendor" and I'm not sure how this should be presented to the user.

**Comment by bigcat88** [comment]
that is already fixed
