### ISSUE TITLE
Recent rating

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/appstore#843]
After adding the app rating, the correct current "Recent rating" does not appear in the application details.

![obraz](https://user-images.githubusercontent.com/47037905/119461800-5b2a7d80-bd40-11eb-92fb-144a033858f4.png)

**Comment by nursoda** [comment]
And it's still like that.

**Comment by bigcat88** [comment]
in the last AppStore version we turned off recent rating, this now is solved
