### ISSUE TITLE
Translation Transifex Setup

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#85]
There should be a way to hook djangos ./manage.py makemessages into Transifex so that the app can be translated by translators.

**Comment by MorrisJobke** [comment]
@LukasReschke Should I take over this one?

**Comment by BernhardPosselt** [comment]
BTW, because translations are sometimes rendered unescaped, we should configure transifex so that it creates pull requests.

**Comment by MorrisJobke** [comment]
> BTW, because translations are sometimes rendered unescaped, we should configure transifex so that it creates pull requests.

To we really want this? This then would create a PR every day. I could add that only reviewed translations are fetched, but I would rate that a but too much effort.

**Comment by MorrisJobke** [comment]
Done -> b75c1c73311fc74e68dd3fc348621b8db5f413fa

Pushes happens on a daily basis
