### ISSUE TITLE
Trying to release app update results in 500 internal server error

### ISSUE THREAD

**Issue by ecsecta** [nextcloud/appstore#869]
I recieve a 500 internal server error response when trying to update the app 'eidlogin'. No further info is given to get any insight what went wrong.

## Details

Browser is Linux FF 92.0, I am logged in as developer of the app at the appstore.

## JavaScript Console Output

This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. new

Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: https://apps.nextcloud.com/static/vendor/bootstrap/dist/css/bootstrap.min.css
Source-Map-Adresse: bootstrap.min.css.map

## Steps to reproduce

This is the post request I sent at Mon, 20 Sep 2021 10:59:03 GMT:
```json
{"download":"https://github.com/eid-login/eid-login-nextcloud/releases/download/1.0.4/eidlogin.tar.gz","nightly":false,"signature":"UicHgx8gi4sfSbgFtuV4npcuDFeawWdAz5fQSHZtOTaGuB1usUghpLzuEv3X57+J\nJw/gDzDO9qGGA+5PFY4cYCjJO8JB/Vj/6pGxs8FyIWgAMigzkRlhUI/rgM9nxL1O\nxcLFePId+JwjRfup7sthy5lHWvD5HyqpcHtOhvdumrGHT633cU5fnilVkK9DmHxb\nFKnEx6Eu5ti0jp9lv9sgZLWiaCFXHD8nRdgjfKbtICG5Cre/bhW2njUwNWcrjL+8\nd64NN+a4tE1Lb1W4qEkX1QiJaqaVWvMJdb/zjeT9TI1KYUn99MaTtags0Vdw8cJw\n75mDPyFc0pqozJTfEkETJJdeONwmR9ovzGBib3Z4Hu4OdBJIRGvfWa/jhlqPsTvQ\nhglCxtr2JOeAadqruqVS6lLvBJID5prIIh4afec/WKHMQSLZykQwydH89VKU4BWA\nW8FGQQwi6fH/mDYlttMUFeLOCzOVJeMrg9ss74FxDX4txwrzuE8ntEhdacPCynnx\nWRwkMY5YyXgPbox8o65BZwpoMQ/nT4tDc4fsvqaeQYdHGppRMsTVghAhF0CFnTJL\ndnt07oWZaq89L1a2xHQT4k7Qh9KvgNC4pTRkAh4oaD0JGS1c0pUDgmp9W5a7zLsG\nyKtkV91ae3DxYXAJBFK5f9/7h0SOovNG84Q4trKOYhI="}
```

Could you please give me a hint what goes wrong here? Is there a problem with the release? If so, what is wrong? Any help is appreciated!

TIA 

Tobias

**Comment by blizzz** [comment]
It appears that part of the API was unavailable, under the radar of monitoring. Please retry.

**Comment by ecsecta** [comment]
Thanks for the quick response, I will try tomorrow.

**Comment by ecsecta** [comment]
Worked now, thank you!
