### ISSUE TITLE
Application generator nexcloud version field stops at 15

### ISSUE THREAD

**Issue by come-nc** [nextcloud/appstore#870]
On https://apps.nextcloud.com/developer/apps/generate , there is a «Nextcloud version» field, but it stops at 15, while last version is 22.

Also it’s not cristal clear what this field means. Is it minimum requirement?

**Comment by tflidd** [comment]
You probably have to create new symlinks here in this repo, like it was done for previous versions:
https://github.com/nextcloud/appstore/issues/548

**Comment by joshtrichards** [comment]
Fixed in #899 it looks like. Can someone close this Issue? (Unless it's being kept open for the question part).
