### ISSUE TITLE
external storage support for gdrive is not tagged as unsafe for NC23

### ISSUE THREAD

**Issue by cyrg38** [nextcloud/appstore#880]
Please provide the following details for error reports from https://apps.nextcloud.com/. Ignore in case of a feature request.

## Details

* Browser and browser version:

## JavaScript Console Output

If unsure see http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers?answertab=votes#tab-top

## Steps to reproduce

1. add external_gdrive app
2. browse anywhere and get server error like this:  

`An unhandled exception has been thrown:
Error: Undefined constant GuzzleHttp\ClientInterface::MAJOR_VERSION in /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Utils.php:113
Stack trace:
#0 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/functions.php(71): GuzzleHttp\Utils::defaultUserAgent()
#1 /var/www/nextcloud/apps/files_external_gdrive/vendor/guzzlehttp/guzzle/src/Client.php(194): GuzzleHttp\default_user_agent()
#2 /var/www/nextcloud/apps/files_external_gdrive/vendor/guzzlehttp/guzzle/src/Client.php(75): GuzzleHttp\Client->configureDefaults()
#3 /var/www/nextcloud/lib/private/Http/Client/ClientService.php(75): GuzzleHttp\Client->__construct()
#4 /var/www/nextcloud/lib/private/OCS/DiscoveryService.php(54): OC\Http\Client\ClientService->newClient()
#5 /var/www/nextcloud/lib/private/Server.php(1304): OC\OCS\DiscoveryService->__construct()
#6 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(160): OC\Server->OC\{closure}()
#7 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#8 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#9 /var/www/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#10 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(438): OC\ServerContainer->query()
#11 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#12 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#13 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#14 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#15 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#16 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#17 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#18 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#19 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#20 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#21 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#22 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#23 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#24 /var/www/nextcloud/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#25 /var/www/nextcloud/lib/private/Console/Application.php(217): OC\ServerContainer->query()
#26 /var/www/nextcloud/lib/private/Console/Application.php(128): OC\Console\Application->loadCommandsFromInfoXml()
#27 /var/www/nextcloud/console.php(98): OC\Console\Application->loadCommands()
`

**Comment by CarlSchwan** [comment]
https://github.com/NastuzziSamy/files_external_gdrive/blob/master/appinfo/info.xml is marked as only working for NC 15 and NC 16. You probably enabled unsafe apps but this is not a appstore issue, that correctly list only versions for NC 15 and NC 16.
