### ISSUE TITLE
apps.nextcloud.com is down (500 internal server error)

### ISSUE THREAD

**Issue by theCalcaholic** [nextcloud/appstore#918]
I'm sure you're already aware of it, but in case you're not: apps.nextcloud.com is currently unavailable due to an internal error. :)

**Comment by CarlSchwan** [comment]
This is a planned downtime for an update. See https://help.nextcloud.com/t/planned-downtime-app-store-tue-16-aug/143367

This just finished and we are now running Ubuntu 22.04 :tada:
