### ISSUE TITLE
apps.nextcloud.com 403 CSRF referrer issue

### ISSUE THREAD

**Issue by the-djmaze** [nextcloud/appstore#929]
Please provide the following details for error reports from https://apps.nextcloud.com/. Ignore in case of a feature request.

## Details

* Browser and browser version: Firefox 104.0.2

CSRF on HTTP_REFERER should be removed.
It has nothing to do with CSRF because HTTP_REFERER is user input and as a developer you should never trust the user.

Because of the issue i can't register, login nor login with Github account.

Please remove this useless security feature and use proper Content Security Policy.

## JavaScript Console Output

Content Security Policy: De instellingen van de pagina blokkeerden het laden van een bron op inline (‘style-src’). https://apps.nextcloud.com/github/login/?process=login

## Steps to reproduce

1. about:config
2. network.http.sendRefererHeader = 0
3. https://apps.nextcloud.com/login/
4. Try to login

**Comment by CarlSchwan** [comment]
Unfortutnately this seems to be out of our hands https://code.djangoproject.com/ticket/16870

**Comment by the-djmaze** [comment]
Still? Wow! i have reported this ages ago to other Django projects and Django still doesn't have a solution.
This really makes Django old and obsolete :cry:
