### ISSUE TITLE
Can't login with GitHub

### ISSUE THREAD

**Issue by the-djmaze** [nextcloud/appstore#930]
Please provide the following details for error reports from https://apps.nextcloud.com/. Ignore in case of a feature request.

## Details

* Browser and browser version: Chromium 106

## JavaScript Console Output

Refused to send form data to 'https://apps.nextcloud.com/github/login/?process=login' because it violates the following Content Security Policy directive: "form-action 'self'".

## Steps to reproduce

1. https://apps.nextcloud.com/login/
2. Click `Log in with GitHub`
3. Click `Continue`

**Comment by ajh123** [comment]
Can confirm it's not just you. I use Edge 106.0.1370.42 (Official build) (64-bit) (which just uses the chromium engine anyway)

**Comment by blizzz** [comment]
@CarlSchwan
