### ISSUE TITLE
Registration via Github: German confirmation email broken

### ISSUE THREAD

**Issue by nuokh** [nextcloud/appstore#961]
Please provide the following details for error reports from https://apps.nextcloud.com/. Ignore in case of a feature request.

## Steps to reproduce

1. Register a new, german Account by using Github
2. Wait for confirmation email

![grafik](https://user-images.githubusercontent.com/9081831/216009426-9200a760-cb27-418b-9758-401a30def49c.png)

This is not just an aesthetic issue. It's not possible to confirm and thus create a new account.

**Comment by blizzz** [comment]
dup of https://github.com/nextcloud/appstore/issues/931
