### ISSUE TITLE
Feature Request: Gitea Integration

### ISSUE THREAD

**Issue by DevynCJohnson** [nextcloud/appstore#983]
Make a plugin like https://github.com/nextcloud/integration_gitlab or https://github.com/nextcloud/integration_github , but for Gitea.  Anybody hosting their own NextCloud that does software development will likely also host their own Git server.

**Comment by DaphneMuller** [comment]
unfortunately this is not an appropriate place to ask for new apps. You are welcome to develop the app yourself and upload it to the app store. If you would like to discuss the development process please go to the forums on help.nextcloud.com
