### ISSUE TITLE
App-Store supported NC versions need update

### ISSUE THREAD

**Issue by tflidd** [nextcloud/appstore#984]
If you ask the appstore-API for the latest supported versions, you get the following (I just skipped older versions):
```

{'hasRelease': False, 'version': '26.0.0', 'isSupported': False},
 {'hasRelease': True, 'version': '25.0.0', 'isSupported': False},
 {'hasRelease': True, 'version': '24.0.4', 'isSupported': True},
```

**Comment by bigcat88** [comment]
@blizzz what do you think about rewriting and automating of this? This is something that should be done fully automatically.
We know EOL(static value), we can just get realeases dates from github and cache them.

**Comment by blizzz** [comment]
There's a cron job that triggers an update of the release in the appstore daily. Maybe something broke there? It does:

```bash
#!/usr/bin/env bash
cd /opt/appstore || exit 194
export DJANGO_SETTINGS_MODULE=nextcloudappstore.settings.production
venv/bin/python manage.py syncnextcloudreleases --oldest-supported="17.0.0"
```

but I am not familiar with this whole stack.

**Comment by bigcat88** [comment]
Probably need run it in terminal by hands and see output.

```
venv/bin/python manage.py syncnextcloudreleases --oldest-supported="17.0.0" --print
```

**Comment by blizzz** [comment]
```
# venv/bin/python manage.py syncnextcloudreleases --oldest-supported="17.0.0" --print
Traceback (most recent call last):
  File "/opt/appstore/manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
```

**Comment by bigcat88** [comment]
Closed as completed, feel free to raise a new issue if something wrong with it.
