### ISSUE TITLE
Cumulative GET paremeters on app list page

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#99]
The GET parameters should be cumulative meaning:
* If I search a term and I change the category, the search term should be kept but the category filtering should change
* If I change the sorting after a search, it should sort the search result appropriately
* If I change the category the ordering should be kept

Solution for this is probably (not sure, just a guess) a template tag.

**Comment by janibonnevier** [comment]
> If I search a term and I change the category, the search term should be kept but the category filtering should change

I myself would expect the search to be discarded if I click on a category, because in my opinion they are conceptually not filters that operate on the currently visible list of apps, but links to other lists.

**Comment by BernhardPosselt** [comment]
So your take on it would be to only update the GET variables inside a category and resetting them when choosing another category correct?

**Comment by janibonnevier** [comment]
Yes, and I think it is because the list of categories looks like navigation, so by clicking there I expect to navigate away from any search results. I'm not so sure about ordering and the "Featured" and "My apps" filters, however...

**Comment by BernhardPosselt** [comment]
Fine by me :)

Do the filters in a category work in a cumulative fashion yet? Also including search?

**Comment by janibonnevier** [comment]
I'm working on it. Basically it works but I'll try to make the solution somewhat pretty too.
