### ISSUE TITLE
Unable to upload update

### ISSUE THREAD

**Issue by csoc-kevink** [nextcloud/appstore#991]
Please provide the following details for error reports from https://apps.nextcloud.com/. Ignore in case of a feature request.

## Details
* Browser and browser version: Chromium 112.0.5615.121

I hope this is the right place for this issue :/

I'll try to upload an update for our app to the appstore via the WebInterfacte at https://apps.nextcloud.com/ and get the following error message: Signature is invalid: [('rsa routines', 'rsa_ossl_public_decrypt', 'data too large for modulus')]

I'm able to create a signature localy with 'openssl dgst -sha512 -sign priv.key -out sign.pem ./myapp.tar.gz'
and verify it successfully with 'openssl dgst -sha512 -verify pub.key -signature sign.pem ./my.tar.gz'. I've tried these steps with a fresh download of the github artifact and it worked localy.

Artifact link: https://github.com/csoc-de/Shifts/releases/download/v1.9.0/shifts-1.9.0.tar.gz
Signature: Attached as file

## JavaScript Console Output
- Only one error: 400 Bad Request

## Steps to reproduce
1. Paste link to GitHub Release-Artifact (~8MB)
2. Paste signature encoded as base64 string (tried with new-lines and without)
3. Press "Upload"
[sign.zip](https://github.com/nextcloud/appstore/files/11380632/sign.zip)

**Comment by joshtrichards** [comment]
I believe you need to use the pipe command as documented rather than `-out`:

https://nextcloudappstore.readthedocs.io/en/latest/developer.html#uploading-an-app-release

You can see what I mean if you do something like:

`dgst -sha512 -sign priv.key -out sign.pem ./myapp.tar.gz`
`cat sign.pem`

Versus:

`dgst -sha512 -sign priv.key ./myapp.tar.gz | openssl base64`

And compare the output. I expect it'll be different. If it is, that's your issue.

**Comment by csoc-kevink** [comment]
Hi @joshtrichards 

thank you for your reply.
I only tried the local verification without base64 encoding. When I try to upload the update, I use
`openssl dgst -sha512 -sign priv.key ./myapp.tar.gz | openssl base64`

Recently i've checked the certificate and found a different checksum for the public key in the signed certificate and the certificate signing request. Maybe thats the problem...

**Comment by joshtrichards** [comment]
Follow-up thread on the forum (noting here for future searchers): https://help.nextcloud.com/t/invalid-signature-error-on-appstore-upload/167079/2
